(() => {
  const $=id=>document.getElementById(id);
  const norm=s=>String(s||'').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9' ]/g,' ').replace(/\s+/g,' ').trim();
  const esc=s=>String(s||'').replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[c]));
  const shuffle=a=>{const b=[...a];for(let i=b.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[b[i],b[j]]=[b[j],b[i]]}return b};
  const pick=a=>a[Math.floor(Math.random()*a.length)];
  const mergedWords=[...(window.QUIZ_WORDS||[]),...(window.QUIZ_EXTRA_WORDS||[])].filter(x=>x&&x.en&&x.fr);
  const mergedPhrases=[...(window.QUIZ_PHRASES||[]),...(window.QUIZ_EXTRA_PHRASES||[])].filter(x=>x&&x.en&&x.fr);
  let profile=localStorage.getItem('academy_profile')||'Yvane';
  let child=localStorage.getItem('academy_child')==='1';

  const COURSES=[
    {level:'A1',title:'Fondations',units:[
      {title:'Saluer et se présenter',rule:'Pour se présenter : “My name is…”, “I am…”, “Nice to meet you.”',examples:[['Hello, my name is Tom.','Bonjour, je m’appelle Tom.'],['How are you?','Comment vas-tu ?'],['Nice to meet you.','Enchanté de te rencontrer.']],q:['What is your name?','Comment t’appelles-tu ?']},
      {title:'Be : am / is / are',rule:'I am • he/she/it is • you/we/they are. À la négation : am not / is not / are not.',examples:[['I am ready.','Je suis prêt.'],['She is happy.','Elle est contente.'],['They are at school.','Ils sont à l’école.']],q:['They ___ tired.','are']},
      {title:'Présent simple',rule:'Le présent simple parle des habitudes. À he/she/it, on ajoute généralement -s.',examples:[['I play football.','Je joue au football.'],['He works here.','Il travaille ici.'],['She likes music.','Elle aime la musique.']],q:['He ___ every day.','works']},
      {title:'Questions simples',rule:'Avec be : “Are you…?” Avec les autres verbes : “Do you…?” / “Does he…?”',examples:[['Are you hungry?','As-tu faim ?'],['Do you like pizza?','Aimes-tu la pizza ?'],['Does she live here?','Est-ce qu’elle habite ici ?']],q:['___ you speak English?','Do']},
      {title:'Nombres, dates et heure',rule:'Apprends les nombres, les années et les structures “It is… o’clock / half past / quarter past”.',examples:[['It is three o’clock.','Il est trois heures.'],['It is half past six.','Il est six heures et demie.'],['Today is Monday.','Aujourd’hui, nous sommes lundi.']],q:['7:30 = It is ___ past seven.','half']}
    ]},
    {level:'A2',title:'Vie quotidienne',units:[
      {title:'Past simple',rule:'Le past simple décrit une action terminée. Verbes réguliers en -ed, verbes irréguliers à apprendre.',examples:[['I watched a movie.','J’ai regardé un film.'],['We went home.','Nous sommes rentrés.'],['She saw him yesterday.','Elle l’a vu hier.']],q:['Yesterday I ___ to school.','went']},
      {title:'Future : will / going to',rule:'Will : décision/prédiction. Going to : intention déjà prévue ou signe visible.',examples:[['I will call you.','Je t’appellerai.'],['I am going to study.','Je vais étudier.'],['It is going to rain.','Il va pleuvoir.']],q:['I am ___ to cook tonight.','going']},
      {title:'Comparatifs',rule:'Adjectif court : -er + than. Adjectif long : more + adjectif + than.',examples:[['This car is faster.','Cette voiture est plus rapide.'],['English is easier now.','L’anglais est plus facile maintenant.'],['This book is more interesting.','Ce livre est plus intéressant.']],q:['My house is ___ than yours.','bigger']},
      {title:'Prépositions utiles',rule:'At pour un point, on pour une surface/jour, in pour un espace/période.',examples:[['at school','à l’école'],['on Monday','lundi'],['in the morning','le matin']],q:['I work ___ Monday.','on']},
      {title:'Voyage pratique',rule:'Utilise des phrases courtes, polies et précises : Could you…? Where is…? I would like…',examples:[['Where is the station?','Où est la gare ?'],['I would like a ticket.','Je voudrais un billet.'],['Could you help me?','Pourriez-vous m’aider ?']],q:['I would ___ a coffee, please.','like']}
    ]},
    {level:'B1',title:'Intermédiaire',units:[
      {title:'Present perfect',rule:'Have/has + participe passé. Il relie le passé au présent : expérience, résultat, durée non terminée.',examples:[['I have finished.','J’ai terminé.'],['She has never been there.','Elle n’y est jamais allée.'],['We have lived here for five years.','Nous vivons ici depuis cinq ans.']],q:['She has ___ the email.','sent']},
      {title:'Conditionnel',rule:'If + present, will + verbe pour une condition réelle. If + past, would + verbe pour l’hypothèse.',examples:[['If it rains, I will stay home.','S’il pleut, je resterai chez moi.'],['If I had time, I would travel.','Si j’avais le temps, je voyagerais.']],q:['If I knew, I ___ tell you.','would']},
      {title:'Phrasal verbs',rule:'Un verbe + particule peut changer complètement de sens : give up, find out, look after…',examples:[['Don’t give up.','N’abandonne pas.'],['I found out yesterday.','Je l’ai découvert hier.'],['Can you look after him?','Peux-tu t’occuper de lui ?']],q:['“Give up” means…','abandonner']},
      {title:'Donner son opinion',rule:'Utilise “I think…”, “In my opinion…”, “From my point of view…” puis justifie avec because/however/although.',examples:[['In my opinion, it is useful.','À mon avis, c’est utile.'],['However, it is expensive.','Cependant, c’est cher.'],['Although it is difficult, I enjoy it.','Même si c’est difficile, j’aime ça.']],q:['___ my opinion, this is better.','In']},
      {title:'Travail et projets',rule:'Apprends le vocabulaire des réunions, délais, responsabilités et comptes rendus.',examples:[['We have a deadline.','Nous avons une date limite.'],['I will send the report.','J’enverrai le rapport.'],['Let’s schedule a meeting.','Planifions une réunion.']],q:['We need to meet the ___.','deadline']}
    ]},
    {level:'B2',title:'Avancé',units:[
      {title:'Voix passive',rule:'Be + participe passé. On insiste sur l’action ou le résultat plutôt que sur l’auteur.',examples:[['The project was completed.','Le projet a été terminé.'],['English is spoken worldwide.','L’anglais est parlé dans le monde entier.']],q:['The car was ___ yesterday.','repaired']},
      {title:'Discours indirect',rule:'Pour rapporter : “He said that…”. Les temps et repères peuvent reculer : today → that day, will → would.',examples:[['She said that she was tired.','Elle a dit qu’elle était fatiguée.'],['He told me he would come.','Il m’a dit qu’il viendrait.']],q:['He said he ___ busy.','was']},
      {title:'Nuancer une idée',rule:'Nevertheless, whereas, despite, therefore, moreover permettent une expression plus précise.',examples:[['Despite the delay, we finished.','Malgré le retard, nous avons terminé.'],['Therefore, we changed the plan.','Par conséquent, nous avons changé le plan.']],q:['___ the rain, they played.','Despite']},
      {title:'Hypothèses avancées',rule:'Third conditional : If + had + participe passé, would have + participe passé.',examples:[['If I had known, I would have called.','Si j’avais su, j’aurais appelé.'],['She would have won if she had trained.','Elle aurait gagné si elle s’était entraînée.']],q:['If I had seen him, I would have ___ hello.','said']},
      {title:'Anglais professionnel',rule:'Travaille la précision : stakeholders, outcomes, constraints, evidence, implementation, assessment.',examples:[['We need reliable evidence.','Nous avons besoin de preuves fiables.'],['The outcome depends on implementation.','Le résultat dépend de la mise en œuvre.']],q:['A “constraint” is…','une contrainte']}
    ]}
  ];

  const CONVERSATIONS=[
    {place:'🍽️ Restaurant',a:'Good evening. Are you ready to order?',fr:'Bonsoir. Êtes-vous prêt à commander ?',choices:[['Yes, I would like the chicken, please.',true],['I am a chicken yesterday.',false],['The station is blue.',false]],reply:'Excellent. Would you like anything to drink?'},
    {place:'✈️ Aéroport',a:'May I see your passport and boarding pass?',fr:'Puis-je voir votre passeport et votre carte d’embarquement ?',choices:[['Of course. Here they are.',true],['I have twenty hungry.',false],['Turn left at breakfast.',false]],reply:'Thank you. Your gate is number twelve.'},
    {place:'🏨 Hôtel',a:'Do you have a reservation?',fr:'Avez-vous une réservation ?',choices:[['Yes, it is under the name Martin.',true],['I reserve yesterday blue.',false],['No, I am at seven o’clock.',false]],reply:'Perfect. Your room is on the third floor.'},
    {place:'🩺 Médecin',a:'What seems to be the problem?',fr:'Quel semble être le problème ?',choices:[['I have had a headache since this morning.',true],['My headache drives the bus.',false],['I am twenty euros.',false]],reply:'I see. Do you have a fever?'},
    {place:'💼 Travail',a:'Can you send me the report before Friday?',fr:'Peux-tu m’envoyer le rapport avant vendredi ?',choices:[['Yes, I will send it by Thursday afternoon.',true],['I sent tomorrow yesterday.',false],['The report eats lunch.',false]],reply:'Great. Please copy the project manager.'},
    {place:'🛍️ Magasin',a:'Can I help you find something?',fr:'Puis-je vous aider à trouver quelque chose ?',choices:[['Yes, I’m looking for a black jacket.',true],['I look black yesterday.',false],['My jacket is a station.',false]],reply:'Certainly. What size do you need?'},
    {place:'🚆 Transport',a:'Excuse me, is this train going to London?',fr:'Excusez-moi, ce train va-t-il à Londres ?',choices:[['Yes, but you need to change at Reading.',true],['The train is eating London.',false],['I am a ticket green.',false]],reply:'Thank you. Which platform should I use?'},
    {place:'📞 Téléphone',a:'Could I speak to Mr Brown, please?',fr:'Puis-je parler à M. Brown, s’il vous plaît ?',choices:[['Certainly. I’ll put you through.',true],['He is a phone blue.',false],['I speak yesterday tomorrow.',false]],reply:'Thank you very much.'}
  ];

  const SURVIVAL=[
    ['Where is the nearest hospital?','Où est l’hôpital le plus proche ?'],['I need help.','J’ai besoin d’aide.'],['Please call the police.','Appelez la police, s’il vous plaît.'],['I have lost my passport.','J’ai perdu mon passeport.'],['Where is the train station?','Où est la gare ?'],['How much does it cost?','Combien ça coûte ?'],['Can I pay by card?','Puis-je payer par carte ?'],['I have a reservation.','J’ai une réservation.'],['Could I have the menu, please?','Puis-je avoir le menu ?'],['I am allergic to peanuts.','Je suis allergique aux cacahuètes.'],['Could you speak more slowly?','Pouvez-vous parler plus lentement ?'],['I do not understand.','Je ne comprends pas.'],['Can you show me on the map?','Pouvez-vous me montrer sur la carte ?'],['What time does it leave?','À quelle heure ça part ?'],['I would like a return ticket.','Je voudrais un aller-retour.'],['Is breakfast included?','Le petit-déjeuner est-il inclus ?'],['My room key does not work.','La clé de ma chambre ne fonctionne pas.'],['Where are the toilets?','Où sont les toilettes ?'],['Can I have the bill, please?','Puis-je avoir l’addition ?'],['I need a pharmacy.','J’ai besoin d’une pharmacie.']
  ];
  const PHRASAL=[['give up','abandonner','Don’t give up.'],['find out','découvrir','I need to find out what happened.'],['look after','s’occuper de','Can you look after the children?'],['turn on','allumer','Turn on the light.'],['turn off','éteindre','Please turn off your phone.'],['put off','reporter','They put off the meeting.'],['set up','mettre en place','We set up a new account.'],['work out','résoudre / s’entraîner','We will work it out.'],['take over','prendre le contrôle','She will take over the project.'],['come across','tomber sur','I came across an old photo.'],['carry out','effectuer','They carried out the test.'],['look into','examiner','We will look into the problem.'],['make up for','compenser','I will make up for the delay.'],['get along with','bien s’entendre avec','I get along with my colleagues.'],['cut down on','réduire','I am cutting down on sugar.']];
  const IRREG=[['be','was/were','been','être'],['become','became','become','devenir'],['begin','began','begun','commencer'],['break','broke','broken','casser'],['bring','brought','brought','apporter'],['buy','bought','bought','acheter'],['come','came','come','venir'],['do','did','done','faire'],['drink','drank','drunk','boire'],['drive','drove','driven','conduire'],['eat','ate','eaten','manger'],['feel','felt','felt','sentir'],['find','found','found','trouver'],['get','got','got/gotten','obtenir'],['give','gave','given','donner'],['go','went','gone','aller'],['have','had','had','avoir'],['know','knew','known','savoir'],['make','made','made','faire/fabriquer'],['read','read','read','lire'],['run','ran','run','courir'],['say','said','said','dire'],['see','saw','seen','voir'],['speak','spoke','spoken','parler'],['take','took','taken','prendre'],['think','thought','thought','penser'],['write','wrote','written','écrire']];
  const PRON=["How are you today?","I would like a cup of coffee, please.","Could you tell me where the station is?","I have been learning English for several months.","This project was completed on time.","Although it was difficult, we found a solution.","The weather is beautiful this afternoon.","Please remember to bring your passport."];

  function speak(text,rate=.82){try{if(window.AndroidTTS&&AndroidTTS.speak){AndroidTTS.speak(String(text),Number(rate));return}}catch(e){}if('speechSynthesis' in window){const u=new SpeechSynthesisUtterance(String(text));u.lang='en-US';u.rate=rate;speechSynthesis.cancel();speechSynthesis.speak(u)}}
  function statsKey(){return `qa3_stats_${profile}`}
  function readStats(){try{return JSON.parse(localStorage.getItem(statsKey()))||{xp:0,streak:0}}catch{return {xp:0,streak:0}}}
  function mistakesKey(){return `qa3_mistakes_${profile}`}
  function readMistakes(){try{return JSON.parse(localStorage.getItem(mistakesKey()))||[]}catch{return []}}
  function masteryKey(){return `qa3_mastery_${profile}`}
  function readMastery(){try{return JSON.parse(localStorage.getItem(masteryKey()))||{}}catch{return {}}}
  function dailyKey(){return `academy_daily_${profile}`}
  function readDaily(){const today=new Date().toISOString().slice(0,10);try{const d=JSON.parse(localStorage.getItem(dailyKey()))||{};return d.day===today?d:{day:today,count:0}}catch{return {day:today,count:0}}}
  function bumpDaily(x=1){const d=readDaily();d.count+=x;localStorage.setItem(dailyKey(),JSON.stringify(d));const s=readStats();s.xp=(s.xp||0)+x*2;localStorage.setItem(statsKey(),JSON.stringify(s));renderStats()}
  function masteredCount(){return Object.values(readMastery()).filter(x=>x.right>=3&&x.right>=x.wrong*2).length}
  function renderStats(){const s=readStats(),d=readDaily(),m=readMistakes();$('xp').textContent=s.xp||0;$('streak').textContent=s.streak||0;$('mastered').textContent=masteredCount();$('mistakes').textContent=m.length;$('goalText').textContent=`${Math.min(d.count,25)}/25`;$('goalFill').style.width=Math.min(100,d.count/25*100)+'%'}

  function setTab(name){document.querySelectorAll('.tab').forEach(x=>x.classList.toggle('active',x.dataset.tab===name));document.querySelectorAll('.panel').forEach(x=>x.classList.toggle('active',x.id===`panel-${name}`));if(name==='revision')renderRevision()}
  document.querySelectorAll('.tab').forEach(b=>b.onclick=()=>setTab(b.dataset.tab));
  $('profile').value=profile;$('profile').onchange=e=>{profile=e.target.value;localStorage.setItem('academy_profile',profile);renderStats();renderRevision()};
  function applyChild(){document.body.classList.toggle('childMode',child);$('childMode').textContent=`🧒 Mode enfant : ${child?'ON':'OFF'}`}$('childMode').onclick=()=>{child=!child;localStorage.setItem('academy_child',child?'1':'0');applyChild()};applyChild();

  function openModal(title,html){$('modalTitle').textContent=title;$('modalBody').innerHTML=html;$('modal').classList.add('open')}
  function closeModal(){$('modal').classList.remove('open')}$('closeModal').onclick=closeModal;$('modal').onclick=e=>{if(e.target===$('modal'))closeModal()};

  function renderCourses(){const g=$('courseGrid');g.innerHTML='';COURSES.forEach(block=>{block.units.forEach((u,i)=>{const div=document.createElement('article');div.className='card course';div.innerHTML=`<span class="tag">${block.level} • unité ${i+1}</span><h3>${esc(u.title)}</h3><p>${esc(u.rule)}</p><button class="action secondary">Ouvrir la leçon</button>`;div.querySelector('button').onclick=()=>openLesson(block,u);g.appendChild(div)})})}
  function openLesson(block,u){const examples=u.examples.map(([en,fr])=>`<div class="lessonLine"><b>${esc(en)}</b><br><span>${esc(fr)}</span> <button class="chip listenEx" data-t="${esc(en)}">🔊</button></div>`).join('');openModal(`${block.level} — ${u.title}`,`<div class="card" style="margin-top:14px"><h3>Règle</h3><p>${esc(u.rule)}</p><div class="lessonList">${examples}</div><div class="exercise" style="margin-top:12px"><b>Mini-question</b><div class="prompt" style="font-size:18px;margin:8px 0">${esc(u.q[0])}</div><div class="inputRow"><input id="lessonAnswer" placeholder="Ta réponse"><button class="action" id="lessonCheck" style="width:auto">Valider</button></div><div class="feedback" id="lessonFb"></div></div></div>`);document.querySelectorAll('.listenEx').forEach(b=>b.onclick=()=>speak(b.dataset.t));$('lessonCheck').onclick=()=>{const ok=norm($('lessonAnswer').value)===norm(u.q[1]);const f=$('lessonFb');f.className='feedback show '+(ok?'ok':'no');f.innerHTML=ok?'✅ Bonne réponse.':`❌ Réponse attendue : <b>${esc(u.q[1])}</b>`;if(ok)bumpDaily(1)}}

  let convIndex=0;
  function renderConversation(){const c=CONVERSATIONS[convIndex%CONVERSATIONS.length];$('conversationBox').innerHTML=`<span class="tag">${c.place}</span><div class="dialogue"><div class="bubble"><small>Interlocuteur</small><b>${esc(c.a)}</b><br><span>${esc(c.fr)}</span> <button class="chip" id="hearConv">🔊</button></div></div><h3>Que réponds-tu ?</h3><div class="answers">${shuffle(c.choices).map(([t,ok])=>`<button class="answer" data-ok="${ok}">${esc(t)}</button>`).join('')}</div><div class="feedback" id="convFb"></div>`;$('hearConv').onclick=()=>speak(c.a);document.querySelectorAll('#conversationBox .answer').forEach(b=>b.onclick=()=>{document.querySelectorAll('#conversationBox .answer').forEach(x=>x.disabled=true);const ok=b.dataset.ok==='true';b.classList.add(ok?'good':'bad');const f=$('convFb');f.className='feedback show '+(ok?'ok':'no');f.innerHTML=ok?`✅ Naturel et correct.<br><b>${esc(c.reply)}</b> <button class="chip" id="hearReply">🔊</button>`:'❌ Cette réponse n’est pas naturelle dans cette situation. Relis la question et choisis une phrase grammaticalement logique.';if(ok){bumpDaily(1);setTimeout(()=>{$('hearReply')&&($('hearReply').onclick=()=>speak(c.reply))},0)}})}
  $('nextConversation').onclick=()=>{convIndex=(convIndex+1)%CONVERSATIONS.length;renderConversation()};

  const dictPool=()=>{const p=mergedPhrases.map(x=>x.en).filter(x=>String(x).split(' ').length>=3&&String(x).length<100);return p.length?p:PRON};let dictation=pick(dictPool());
  function newDict(){dictation=pick(dictPool());$('dictationInput').value='';$('dictationFeedback').className='feedback';$('listenHint').textContent='Appuie sur lecture puis écris exactement la phrase.'}$('listenNormal').onclick=()=>speak(dictation,.82);$('listenSlow').onclick=()=>speak(dictation,.62);$('newDictation').onclick=newDict;
  function wordDiff(user,target){const a=norm(user).split(' ').filter(Boolean),b=norm(target).split(' ').filter(Boolean);return b.map((w,i)=>a[i]===w?`<span style="color:var(--green)">${esc(w)}</span>`:`<span style="color:var(--red);text-decoration:underline">${esc(w)}</span>`).join(' ')}
  $('checkDictation').onclick=()=>{const u=$('dictationInput').value,ok=norm(u)===norm(dictation),f=$('dictationFeedback');f.className='feedback show '+(ok?'ok':'no');f.innerHTML=ok?`✅ Parfait : <b>${esc(dictation)}</b>`:`❌ La phrase correcte est :<br><b>${wordDiff(u,dictation)}</b><br><small>Les mots soulignés sont absents, déplacés ou différents.</small>`;if(ok)bumpDaily(2)};

  let pron=pick(PRON);function setPron(){pron=pick(PRON);$('pronPhrase').textContent=pron;$('pronScore').textContent='—';$('pronRing').style.setProperty('--p','0%');$('pronFeedback').className='feedback';$('micStatus').textContent='Appuie sur le micro.'} $('newPron').onclick=setPron;$('hearPron').onclick=()=>speak(pron,.72);
  function scorePron(recognized){const target=norm(pron).split(' ').filter(Boolean),heard=norm(recognized).split(' ').filter(Boolean);let hit=0;const missing=[];target.forEach((w,i)=>{if(heard.includes(w)||heard[i]===w)hit++;else missing.push(w)});const score=Math.round(hit/Math.max(1,target.length)*100);$('pronScore').textContent=score+'%';$('pronRing').style.setProperty('--p',score+'%');const f=$('pronFeedback');f.className='feedback show '+(score>=75?'ok':'no');f.innerHTML=`Tu as dit : <b>${esc(recognized||'—')}</b><br>${missing.length?`À retravailler : <b>${missing.map(esc).join(', ')}</b>`:'✅ Tous les mots principaux ont été reconnus.'}`;if(score>=75)bumpDaily(2)}
  window.onNativeSpeechResult=text=>{ $('micStatus').textContent='Reconnaissance terminée.';scorePron(text)};window.onNativeSpeechError=msg=>{$('micStatus').textContent='Micro : '+msg};
  function startBrowserRecognition(){const SR=window.SpeechRecognition||window.webkitSpeechRecognition;if(!SR){$('micStatus').textContent='Reconnaissance vocale non disponible sur ce WebView.';return}const r=new SR();r.lang='en-US';r.interimResults=false;r.maxAlternatives=1;$('micStatus').textContent='🎙️ Parle maintenant…';r.onresult=e=>scorePron(e.results[0][0].transcript);r.onerror=e=>$('micStatus').textContent='Erreur micro : '+e.error;r.start()}
  $('startMic').onclick=()=>{try{if(window.AndroidSpeech&&AndroidSpeech.startRecognition){$('micStatus').textContent='🎙️ Parle maintenant…';AndroidSpeech.startRecognition('en-US');return}}catch(e){}startBrowserRecognition()};

  function renderRevision(){const list=readMistakes(),box=$('mistakeList');if(!list.length)box.innerHTML='<div class="empty">Aucune erreur enregistrée pour ce profil. Continue les quiz.</div>';else box.innerHTML=list.slice(-25).reverse().map(m=>{const x=m.item||{};const en=x.en||x.question||x.prompt||'Exercice';const fr=x.fr||x.answerFr||x.answer||'';return `<div class="reviewItem"><div><b>${esc(en)}</b><br><small>${esc(fr)}</small></div><button class="chip revSpeak" data-t="${esc(x.en||x.answer||'')}">🔊</button></div>`}).join('');document.querySelectorAll('.revSpeak').forEach(b=>b.onclick=()=>speak(b.dataset.t));renderSrs()}
  function srsKey(){return `academy_srs_${profile}`}
  function getSrs(){try{return JSON.parse(localStorage.getItem(srsKey()))||{}}catch{return {}}}
  let srsWord=null;
  function dueWords(){const data=getSrs(),now=Date.now();return mergedWords.filter(w=>!data[norm(w.en)]||data[norm(w.en)].due<=now)}
  function renderSrs(){const pool=dueWords();srsWord=pick(pool.length?pool:mergedWords);if(!srsWord){$('srsBox').innerHTML='<div class="empty">Aucune carte disponible.</div>';return}$('srsBox').innerHTML=`<div class="prompt">${esc(srsWord.en)}</div><div class="hint" id="srsReveal">Appuie sur “Voir” pour afficher la traduction.</div><button class="action secondary" id="srsHear">🔊 Écouter</button><button class="action" id="srsShow" style="margin-top:8px">Voir la réponse</button><div class="srsButtons" id="srsRate" style="display:none;margin-top:10px"><button data-days="0.02" style="background:#ff9ea2">Difficile</button><button data-days="1" style="background:#ffd76a">Moyen</button><button data-days="3" style="background:#9eefff">Bien</button><button data-days="7" style="background:#9cf57d">Acquis</button></div>`;$('srsHear').onclick=()=>speak(srsWord.en);$('srsShow').onclick=()=>{$('srsReveal').innerHTML=`<b>${esc(srsWord.fr)}</b> • ${esc(srsWord.theme||'vocabulaire')}`;$('srsRate').style.display='flex'};document.querySelectorAll('#srsRate button').forEach(b=>b.onclick=()=>{const d=getSrs(),id=norm(srsWord.en),days=Number(b.dataset.days);d[id]={due:Date.now()+days*86400000,interval:days};localStorage.setItem(srsKey(),JSON.stringify(d));bumpDaily(1);renderSrs()})}

  function listModal(title,rows,type){let html='<div class="card" style="margin-top:14px">';if(type==='fav'){const favs=getFavs();html+=favs.length?favs.map(x=>`<div class="favItem"><div><b>${esc(x.en)}</b><br><small>${esc(x.fr)}</small></div><button class="chip toolSpeak" data-t="${esc(x.en)}">🔊</button></div>`).join(''):'<div class="empty">Aucun favori. Utilise ⭐ dans la recherche.</div>'}else html+=rows.map(r=>`<div class="searchItem"><div><b>${esc(r[0])}</b><br><small>${esc(r[1]||'')}</small>${r[2]?`<br><span>${esc(r[2])}</span>`:''}</div><button class="chip toolSpeak" data-t="${esc(r[0])}">🔊</button></div>`).join('');html+='</div>';openModal(title,html);document.querySelectorAll('.toolSpeak').forEach(b=>b.onclick=()=>speak(b.dataset.t))}
  function favKey(){return `academy_favs_${profile}`};function getFavs(){try{return JSON.parse(localStorage.getItem(favKey()))||[]}catch{return []}}function addFav(en,fr){const a=getFavs();if(!a.some(x=>norm(x.en)===norm(en))){a.push({en,fr});localStorage.setItem(favKey(),JSON.stringify(a))}}
  $('openFavs').onclick=()=>listModal('⭐ Mes favoris',[], 'fav');$('openSurvival').onclick=()=>listModal('🧭 Anglais de survie',SURVIVAL);$('openPhrasal').onclick=()=>listModal('🔗 Phrasal verbs',PHRASAL);$('openIrregular').onclick=()=>listModal('⚡ Verbes irréguliers',IRREG.map(x=>[`${x[0]} → ${x[1]} → ${x[2]}`,x[3],x[0]]));

  $('globalSearch').oninput=e=>{const q=norm(e.target.value),out=$('searchResults');if(q.length<2){out.innerHTML='<div class="empty">Écris au moins deux lettres.</div>';return}const all=[...mergedWords.map(x=>({en:x.en,fr:x.fr,meta:x.theme||x.level||'mot'})),...mergedPhrases.map(x=>({en:x.en,fr:x.fr,meta:'phrase'}))];const hits=all.filter(x=>norm(x.en).includes(q)||norm(x.fr).includes(q)).slice(0,30);out.innerHTML=hits.length?hits.map(x=>`<div class="searchItem"><div><b>${esc(x.en)}</b><br><small>${esc(x.fr)} • ${esc(x.meta)}</small></div><div><button class="chip srSpeak" data-t="${esc(x.en)}">🔊</button><button class="chip srFav" data-en="${esc(x.en)}" data-fr="${esc(x.fr)}">⭐</button></div></div>`).join(''):'<div class="empty">Aucun résultat.</div>';document.querySelectorAll('.srSpeak').forEach(b=>b.onclick=()=>speak(b.dataset.t));document.querySelectorAll('.srFav').forEach(b=>b.onclick=()=>{addFav(b.dataset.en,b.dataset.fr);b.textContent='✅'})};

  function examQuestions(count=20){const words=shuffle(mergedWords).slice(0,count);return words.map(w=>{const wrong=shuffle(mergedWords.filter(x=>x!==w&&x.level===w.level)).slice(0,3).map(x=>x.fr);return {q:`Que signifie “${w.en}” ?`,a:w.fr,choices:shuffle([w.fr,...wrong])}})}
  function runExam(title,adaptive=false){const qs=examQuestions(adaptive?24:20);let i=0,score=0,answers=[];const draw=()=>{if(i>=qs.length){const pct=Math.round(score/qs.length*100);const level=pct<35?'A1':pct<55?'A2':pct<75?'B1':'B2';openModal(title,`<div class="card" style="margin-top:14px;text-align:center"><div class="scoreRing" style="--p:${pct}%"><b>${pct}%</b></div><h2>${adaptive?`Niveau estimé : ${level}`:'Examen terminé'}</h2><p>${score}/${qs.length} bonnes réponses.</p><button class="action" id="examClose">Terminer</button></div>`);$('examClose').onclick=closeModal;bumpDaily(Math.max(1,Math.round(score/4)));return}const x=qs[i];openModal(`${title} — ${i+1}/${qs.length}`,`<div class="exercise" style="margin-top:14px"><div class="prompt">${esc(x.q)}</div><div class="answers" style="margin-top:12px">${x.choices.map(c=>`<button class="answer examAns" data-v="${esc(c)}">${esc(c)}</button>`).join('')}</div><div class="feedback" id="examFb"></div></div>`);document.querySelectorAll('.examAns').forEach(b=>b.onclick=()=>{const ok=norm(b.dataset.v)===norm(x.a);answers.push(ok);if(ok)score++;b.classList.add(ok?'good':'bad');document.querySelectorAll('.examAns').forEach(z=>z.disabled=true);const f=$('examFb');f.className='feedback show '+(ok?'ok':'no');f.innerHTML=ok?'✅ Correct.':`❌ Bonne réponse : <b>${esc(x.a)}</b>`;setTimeout(()=>{i++;draw()},650)})};draw()}
  $('startPlacement').onclick=()=>runExam('🎯 Test de placement',true);$('startExam').onclick=()=>runExam('⏱️ Mode examen',false);

  renderCourses();renderConversation();renderStats();renderRevision();setPron();newDict();
})();
