window.ADULT_SCENARIOS=[
{
id:'hotel',icon:'🏨',title:'Arrivée à l’hôtel',place:'Réception d’un hôtel à Londres',level:'A2',duration:'3–4 min',goal:'Faire le check-in, poser des questions et résoudre un petit problème.',
vocab:{reservation:{fr:'réservation',pron:'ré-zeur-véï-cheun'},available:{fr:'disponible',pron:'e-véï-le-beul'},included:{fr:'inclus',pron:'in-klou-did'},receipt:{fr:'reçu / ticket',pron:'ri-siit'},floor:{fr:'étage',pron:'flor'},quiet:{fr:'calme',pron:'kwaï-eut'},luggage:{fr:'bagages',pron:'leu-guidj'},issue:{fr:'problème',pron:'i-chou'}},
steps:[
{speaker:'Receptionist',text:'Good evening. Welcome to the Riverside Hotel. Do you have a reservation?',answer:'Yes, I have a reservation under the name Mboup.',pron:'Yes, aï hav e ré-zeur-véï-cheun eunde ze néïm Mboup.',fr:'Oui, j’ai une réservation au nom de Mboup.',choices:['Yes, I have a reservation under the name Mboup.','I want a table for two, please.','No, I am looking for the train station.']},
{speaker:'Receptionist',text:'Thank you. May I see your passport, please?',answer:'Of course. Here is my passport.',pron:'Of cors. Hière iz maï passe-port.',fr:'Bien sûr. Voici mon passeport.',choices:['Of course. Here is my passport.','I do not like passports.','The room is very expensive.']},
{speaker:'Receptionist',text:'Perfect. I have you for three nights in a double room. Is that correct?',answer:'Yes, that is correct. Is breakfast included?',pron:'Yes, zat iz ko-rect. Iz brek-feust in-klou-did?',fr:'Oui, c’est correct. Le petit-déjeuner est-il inclus ?',choices:['Yes, that is correct. Is breakfast included?','No, I need to buy a bus ticket.','Can you repair my phone?']},
{speaker:'Receptionist',text:'Yes, breakfast is included and it is served from seven to ten.',answer:'Great. Where is the breakfast room?',pron:'Gréït. Ouère iz ze brek-feust roum?',fr:'Super. Où se trouve la salle du petit-déjeuner ?',choices:['Great. Where is the breakfast room?','What time does the museum close?','I would like a prescription.']},
{speaker:'Receptionist',text:'It is on the ground floor, next to the lifts. Your room is on the fourth floor.',answer:'Thank you. Is the room quiet?',pron:'Sènk iou. Iz ze roum kwaï-eut?',fr:'Merci. La chambre est-elle calme ?',choices:['Thank you. Is the room quiet?','Can I order a pizza here?','Is this train going to Paris?']},
{speaker:'Receptionist',text:'It should be quiet. It faces the courtyard, not the street.',answer:'Perfect. I prefer a quiet room.',pron:'Peu-fect. Aï pri-feur e kwaï-eut roum.',fr:'Parfait. Je préfère une chambre calme.',choices:['Perfect. I prefer a quiet room.','I prefer a very noisy airport.','I need a football referee.']},
{speaker:'Receptionist',text:'Here is your key card. The Wi-Fi password is written on the card holder.',answer:'Thanks. Could you also tell me the check-out time?',pron:'Sènks. Koud iou ol-so tel mi ze tchek-aout taïm?',fr:'Merci. Pourriez-vous aussi me dire l’heure du départ ?',choices:['Thanks. Could you also tell me the check-out time?','How much is this jacket?','Where can I buy medicine?']},
{speaker:'Receptionist',text:'Check-out is before eleven in the morning.',answer:'That is fine. Can I leave my luggage here after check-out?',pron:'Zat iz faïne. Kan aï liiv maï leu-guidj hière after tchek-aout?',fr:'Très bien. Puis-je laisser mes bagages ici après le départ ?',choices:['That is fine. Can I leave my luggage here after check-out?','Can I swim in the reception?','I want to change my flight.']},
{speaker:'Receptionist',text:'Yes, we can keep your luggage at reception for free.',answer:'Excellent, thank you. One more question: is there a pharmacy nearby?',pron:'Ek-se-lent, sènk iou. Ouan mor kwes-tcheun: iz zère e far-me-si nièr-baï?',fr:'Excellent, merci. Une dernière question : y a-t-il une pharmacie à proximité ?',choices:['Excellent, thank you. One more question: is there a pharmacy nearby?','Do you sell football boots?','Is the weather included?']},
{speaker:'Receptionist',text:'Yes. Turn right outside the hotel and walk for about five minutes.',answer:'Okay, that sounds easy to find.',pron:'O-kéï, zat saounds i-zi tou faïnd.',fr:'D’accord, cela semble facile à trouver.',choices:['Okay, that sounds easy to find.','I never walk on weekdays.','Please cancel the restaurant.']},
{speaker:'Receptionist',text:'If you have any issue with the room, dial zero from the room phone.',answer:'Understood. I will call reception if there is a problem.',pron:'Eun-deur-stoud. Aï ouil kol ri-sep-cheun if zère iz e pro-blem.',fr:'Compris. J’appellerai la réception s’il y a un problème.',choices:['Understood. I will call reception if there is a problem.','I will call the airport for breakfast.','I will buy another hotel.']},
{speaker:'Receptionist',text:'Enjoy your stay, and have a nice evening.',answer:'Thank you very much. Have a nice evening too.',pron:'Sènk iou ve-ri meutch. Hav e naïss iiv-ning tou.',fr:'Merci beaucoup. Passez une bonne soirée également.',choices:['Thank you very much. Have a nice evening too.','No, I do not have an evening.','Please bring my car tomorrow.']}
]},
{
id:'restaurant',icon:'🍽️',title:'Restaurant avec un problème',place:'Restaurant à Manchester',level:'A2–B1',duration:'3–4 min',goal:'Commander, demander des précisions, signaler une erreur et payer.',
vocab:{starter:{fr:'entrée',pron:'star-teur'},main:{fr:'plat principal',pron:'méïn'},allergic:{fr:'allergique',pron:'e-leur-djik'},recommend:{fr:'recommander',pron:'re-keu-mend'},instead:{fr:'à la place',pron:'in-sted'},bill:{fr:'addition',pron:'bil'},charged:{fr:'facturé',pron:'tchardjd'},separate:{fr:'séparé',pron:'sé-peu-reut'}},
steps:[
{speaker:'Waiter',text:'Good evening. Do you have a table booked?',answer:'Yes, I booked a table for two at seven thirty.',pron:'Yes, aï boukt e téï-beul for tou at se-ven seur-ti.',fr:'Oui, j’ai réservé une table pour deux à 19 h 30.',choices:['Yes, I booked a table for two at seven thirty.','Yes, my train leaves at seven thirty.','I need two hotel rooms.']},
{speaker:'Waiter',text:'Great. Please follow me. Would you like something to drink first?',answer:'Yes, sparkling water for me, please.',pron:'Yes, spar-kling wo-teur for mi, pliiz.',fr:'Oui, de l’eau gazeuse pour moi, s’il vous plaît.',choices:['Yes, sparkling water for me, please.','I am looking for platform six.','Can you check my passport?']},
{speaker:'Waiter',text:'Here are the menus. Our soup of the day is tomato and basil.',answer:'Thanks. What do you recommend as a main course?',pron:'Sènks. Ouat dou iou re-keu-mend az e méïn kors?',fr:'Merci. Que recommandez-vous comme plat principal ?',choices:['Thanks. What do you recommend as a main course?','Where is the nearest bank?','What is your Wi-Fi password?']},
{speaker:'Waiter',text:'The grilled chicken is very popular, and the fish is excellent too.',answer:'Does the fish come with vegetables?',pron:'Deuz ze fich keum ouiz vedj-te-beuls?',fr:'Le poisson est-il servi avec des légumes ?',choices:['Does the fish come with vegetables?','Does the bus come with luggage?','Is the doctor available?']},
{speaker:'Waiter',text:'Yes, with roasted vegetables and potatoes.',answer:'That sounds good. I will have the fish.',pron:'Zat saounds goud. Aï ouil hav ze fich.',fr:'Ça a l’air bon. Je vais prendre le poisson.',choices:['That sounds good. I will have the fish.','I will have a new passport.','I will take the underground home.']},
{speaker:'Waiter',text:'Any starter?',answer:'No starter for me. I am not very hungry.',pron:'No star-teur for mi. Aï am not ve-ri hung-gri.',fr:'Pas d’entrée pour moi. Je n’ai pas très faim.',choices:['No starter for me. I am not very hungry.','No station for me.','No hotel because I am late.']},
{speaker:'Waiter',text:'Before I place the order, do you have any allergies?',answer:'Yes, I am allergic to peanuts.',pron:'Yes, aï am e-leur-djik tou pii-nuts.',fr:'Oui, je suis allergique aux cacahuètes.',choices:['Yes, I am allergic to peanuts.','Yes, I am late for work.','Yes, I can drive a bus.']},
{speaker:'Waiter',text:'Thank you for telling me. I will check with the kitchen.',answer:'Thank you. I appreciate that.',pron:'Sènk iou. Aï e-pri-chi-éït zat.',fr:'Merci. J’apprécie.',choices:['Thank you. I appreciate that.','Please bring my suitcase.','I need a larger room.']},
{speaker:'Waiter',text:'I am sorry, the sauce may contain peanuts. We can serve lemon butter instead.',answer:'Lemon butter instead would be perfect.',pron:'Le-mon beu-teur in-sted woud bi peu-fect.',fr:'Du beurre citronné à la place serait parfait.',choices:['Lemon butter instead would be perfect.','I need another boarding pass.','The meeting starts tomorrow.']},
{speaker:'Waiter',text:'How is everything?',answer:'The fish is very good, but I ordered sparkling water and received still water.',pron:'Ze fich iz ve-ri goud, beut aï or-deurd spar-kling wo-teur and ri-siivd stil wo-teur.',fr:'Le poisson est très bon, mais j’ai commandé de l’eau gazeuse et reçu de l’eau plate.',choices:['The fish is very good, but I ordered sparkling water and received still water.','My room is on the fourth floor.','The train is delayed.']},
{speaker:'Waiter',text:'I apologise. I will replace it immediately.',answer:'No problem, thank you for fixing it.',pron:'No pro-blem, sènk iou for fik-sing it.',fr:'Pas de problème, merci d’avoir corrigé cela.',choices:['No problem, thank you for fixing it.','Please cancel my flight.','I cannot find my suitcase.']},
{speaker:'Waiter',text:'Would you like dessert or coffee?',answer:'Just a coffee, please, and could we have the bill?',pron:'Djeust e ko-fi, pliiz, and koud oui hav ze bil?',fr:'Juste un café, s’il vous plaît, et pourrions-nous avoir l’addition ?',choices:['Just a coffee, please, and could we have the bill?','I need a taxi to the airport tomorrow.','Can I change my room?']},
{speaker:'Waiter',text:'Certainly. Would you like to pay together or separately?',answer:'Separately, please. I will pay by card.',pron:'Sé-peu-reut-li, pliiz. Aï ouil péï baï kard.',fr:'Séparément, s’il vous plaît. Je vais payer par carte.',choices:['Separately, please. I will pay by card.','I will pay with my passport.','Please send the bill to the train station.']}
]},
{
id:'work',icon:'💼',title:'Réunion au travail',place:'Réunion avec un collègue anglophone',level:'B1',duration:'3–4 min',goal:'Expliquer un retard, proposer une solution et négocier un délai.',
vocab:{deadline:{fr:'date limite',pron:'ded-laïne'},delay:{fr:'retard',pron:'di-léï'},update:{fr:'mise à jour',pron:'eup-déït'},priority:{fr:'priorité',pron:'praï-o-ri-ti'},manage:{fr:'réussir à / gérer',pron:'ma-nidj'},available:{fr:'disponible',pron:'e-véï-le-beul'},schedule:{fr:'planning',pron:'sked-joul'},estimate:{fr:'estimation',pron:'es-ti-meït'}},
steps:[
{speaker:'Manager',text:'Morning. Can you give me a quick update on the project?',answer:'Sure. Most of the work is finished, but we have a small delay.',pron:'Chour. Most ov ze work iz fi-nicht, beut oui hav e smol di-léï.',fr:'Bien sûr. La majeure partie du travail est terminée, mais nous avons un petit retard.',choices:['Sure. Most of the work is finished, but we have a small delay.','I would like the fish, please.','My room is very quiet.']},
{speaker:'Manager',text:'What caused the delay?',answer:'We received the final information later than expected.',pron:'Oui ri-siivd ze faï-neul in-for-méï-cheun léï-teur zan ik-spek-tid.',fr:'Nous avons reçu les informations finales plus tard que prévu.',choices:['We received the final information later than expected.','The train station closes at six.','I forgot my passport at home.']},
{speaker:'Manager',text:'How much extra time do you need?',answer:'I estimate that we need two more working days.',pron:'Aï es-ti-meït zat oui niid tou mor work-ing déïz.',fr:'J’estime que nous avons besoin de deux jours ouvrés supplémentaires.',choices:['I estimate that we need two more working days.','I need two desserts.','The hotel has two lifts.']},
{speaker:'Manager',text:'The original deadline is Friday. Can we still deliver something by then?',answer:'Yes. We can deliver the priority items on Friday.',pron:'Yes. Oui kan di-li-veur ze praï-o-ri-ti aï-temz on Fraï-déï.',fr:'Oui. Nous pouvons livrer les éléments prioritaires vendredi.',choices:['Yes. We can deliver the priority items on Friday.','No, I do not have any luggage.','I want a table near the window.']},
{speaker:'Manager',text:'Which parts would be delayed?',answer:'Only the final report and the detailed statistics.',pron:'On-li ze faï-neul ri-port and ze di-téïld sta-tis-tiks.',fr:'Seulement le rapport final et les statistiques détaillées.',choices:['Only the final report and the detailed statistics.','Only breakfast and coffee.','Only my passport and ticket.']},
{speaker:'Manager',text:'Could someone else help you with the report?',answer:'Yes, if Sarah is available this afternoon, we can save some time.',pron:'Yes, if Sa-ra iz e-véï-le-beul zis af-teur-noun, oui kan séïv seum taïm.',fr:'Oui, si Sarah est disponible cet après-midi, nous pouvons gagner du temps.',choices:['Yes, if Sarah is available this afternoon, we can save some time.','Sarah can repair my hotel room.','I can order Sarah at the restaurant.']},
{speaker:'Manager',text:'I can ask her. What do you need from me?',answer:'I need confirmation about the new priority and the deadline.',pron:'Aï niid kon-feur-méï-cheun e-baout ze niou praï-o-ri-ti and ze ded-laïne.',fr:'J’ai besoin d’une confirmation concernant la nouvelle priorité et la date limite.',choices:['I need confirmation about the new priority and the deadline.','I need a receipt for my lunch.','I need directions to the museum.']},
{speaker:'Manager',text:'The priority is the customer presentation. The report can wait until Tuesday.',answer:'That helps a lot. We can manage that schedule.',pron:'Zat helps e lot. Oui kan ma-nidj zat sked-joul.',fr:'Cela aide beaucoup. Nous pouvons gérer ce planning.',choices:['That helps a lot. We can manage that schedule.','I cannot eat that schedule.','Tuesday is my hotel room.']},
{speaker:'Manager',text:'Can you send me an update at the end of today?',answer:'Yes, I will send a short update before five.',pron:'Yes, aï ouil send e short eup-déït bi-for faïv.',fr:'Oui, j’enverrai une courte mise à jour avant 17 h.',choices:['Yes, I will send a short update before five.','I will send my suitcase before five.','I will call the pharmacy tomorrow.']},
{speaker:'Manager',text:'Please include any risks that could cause another delay.',answer:'Of course. I will list the main risks and possible solutions.',pron:'Ov cors. Aï ouil list ze méïn risks and po-si-beul se-lou-cheunz.',fr:'Bien sûr. Je vais lister les principaux risques et les solutions possibles.',choices:['Of course. I will list the main risks and possible solutions.','I will list the desserts and drinks.','I will list all the train platforms.']},
{speaker:'Manager',text:'Good. Do you think we need another meeting tomorrow?',answer:'A short meeting would be useful if anything changes.',pron:'E short miit-ing woud bi ious-feul if e-ni-sing tchéïn-djiz.',fr:'Une courte réunion serait utile si quelque chose change.',choices:['A short meeting would be useful if anything changes.','A meeting is included with breakfast.','I am allergic to meetings.']},
{speaker:'Manager',text:'Agreed. Let us keep it flexible and decide after your update.',answer:'Sounds good. I will keep you informed.',pron:'Saounds goud. Aï ouil kiip iou in-formd.',fr:'Ça me va. Je vous tiendrai informé.',choices:['Sounds good. I will keep you informed.','I will keep your passport.','I will ask for the bill.']}
]},
{
id:'doctor',icon:'🩺',title:'Chez le médecin',place:'Cabinet médical pendant un voyage',level:'A2–B1',duration:'3–4 min',goal:'Décrire des symptômes, comprendre les conseils et poser des questions.',
vocab:{appointment:{fr:'rendez-vous',pron:'e-poïnt-ment'},symptoms:{fr:'symptômes',pron:'simp-teumz'},pain:{fr:'douleur',pron:'péïn'},worse:{fr:'pire',pron:'weurs'},prescription:{fr:'ordonnance',pron:'pri-skrip-cheun'},rest:{fr:'repos',pron:'rest'},improve:{fr:'s’améliorer',pron:'im-prouv'},emergency:{fr:'urgence',pron:'i-meur-djen-si'}},
steps:[
{speaker:'Doctor',text:'Hello. What brings you in today?',answer:'I have had a sore throat and a cough for three days.',pron:'Aï hav had e sor srot and e kof for sri déïz.',fr:'J’ai mal à la gorge et je tousse depuis trois jours.',choices:['I have had a sore throat and a cough for three days.','I need a double room for three nights.','I would like the fish.']},
{speaker:'Doctor',text:'Do you have a fever?',answer:'I had a slight fever last night, but not this morning.',pron:'Aï had e slaït fii-veur last naït, beut not zis mor-ning.',fr:'J’ai eu un peu de fièvre hier soir, mais pas ce matin.',choices:['I had a slight fever last night, but not this morning.','My train was delayed last night.','I paid by card this morning.']},
{speaker:'Doctor',text:'Are you having any difficulty breathing?',answer:'No, my breathing is normal.',pron:'No, maï brii-zing iz nor-meul.',fr:'Non, ma respiration est normale.',choices:['No, my breathing is normal.','No, breakfast is not included.','No, the report is not ready.']},
{speaker:'Doctor',text:'Does the pain get worse when you swallow?',answer:'Yes, especially when I drink something cold.',pron:'Yes, es-pe-cheu-li wen aï drink seum-sing kold.',fr:'Oui, surtout quand je bois quelque chose de froid.',choices:['Yes, especially when I drink something cold.','Yes, especially on platform six.','Yes, the room is quiet.']},
{speaker:'Doctor',text:'I will examine your throat and listen to your chest.',answer:'Okay. Do you think it could be an infection?',pron:'O-kéï. Dou iou sink it koud bi an in-fek-cheun?',fr:'D’accord. Pensez-vous que cela pourrait être une infection ?',choices:['Okay. Do you think it could be an infection?','Do you think the restaurant is open?','Could I have a receipt?']},
{speaker:'Doctor',text:'It looks like a viral infection, so antibiotics probably will not help.',answer:'What should I do to feel better?',pron:'Ouat choud aï dou tou fiil be-teur?',fr:'Que dois-je faire pour me sentir mieux ?',choices:['What should I do to feel better?','Where should I leave my luggage?','When is the project deadline?']},
{speaker:'Doctor',text:'Rest, drink plenty of water, and you can take paracetamol for the pain.',answer:'How often can I take it?',pron:'Haou of-ten kan aï téïk it?',fr:'À quelle fréquence puis-je en prendre ?',choices:['How often can I take it?','How often does the train stop?','How often is breakfast included?']},
{speaker:'Doctor',text:'Follow the instructions on the packet and do not take more than the recommended dose.',answer:'Understood. Do I need a prescription?',pron:'Eun-deur-stoud. Dou aï niid e pri-skrip-cheun?',fr:'Compris. Ai-je besoin d’une ordonnance ?',choices:['Understood. Do I need a prescription?','Do I need a hotel reservation?','Do I need a meeting room?']},
{speaker:'Doctor',text:'Not for paracetamol. You can buy it at a pharmacy.',answer:'How long should these symptoms last?',pron:'Haou long choud ziiz simp-teumz last?',fr:'Combien de temps ces symptômes devraient-ils durer ?',choices:['How long should these symptoms last?','How long is the train platform?','How long is the restaurant bill?']},
{speaker:'Doctor',text:'You should start to improve in a few days.',answer:'And when should I come back?',pron:'And wen choud aï keum bak?',fr:'Et quand dois-je revenir ?',choices:['And when should I come back?','When should I check out?','When should I pay the bill?']},
{speaker:'Doctor',text:'Come back if you are not improving after a week, or sooner if you feel much worse.',answer:'Is there anything that would be an emergency?',pron:'Iz zère e-ni-sing zat woud bi an i-meur-djen-si?',fr:'Y a-t-il quelque chose qui constituerait une urgence ?',choices:['Is there anything that would be an emergency?','Is there anything included in breakfast?','Is there another project deadline?']},
{speaker:'Doctor',text:'Yes. Seek urgent help if you have serious difficulty breathing or severe chest pain.',answer:'I understand. Thank you for explaining everything clearly.',pron:'Aï eun-deur-stand. Sènk iou for ik-spléï-ning ev-ri-sing klièr-li.',fr:'Je comprends. Merci d’avoir tout expliqué clairement.',choices:['I understand. Thank you for explaining everything clearly.','I understand. Please bring the dessert.','I understand. The train is on time.']}
]},
{
id:'airport',icon:'✈️',title:'Vol retardé à l’aéroport',place:'Comptoir d’une compagnie aérienne',level:'B1',duration:'3–4 min',goal:'Comprendre un retard, demander des options et protéger une correspondance.',
vocab:{delayed:{fr:'retardé',pron:'di-léïd'},connection:{fr:'correspondance',pron:'ke-nek-cheun'},rebook:{fr:'réserver sur un autre vol',pron:'ri-bouk'},boarding:{fr:'embarquement',pron:'bor-ding'},voucher:{fr:'bon / coupon',pron:'vaou-tcheur'},overnight:{fr:'pour la nuit',pron:'o-veur-naït'},available:{fr:'disponible',pron:'e-véï-le-beul'},destination:{fr:'destination',pron:'des-ti-néï-cheun'}},
steps:[
{speaker:'Agent',text:'Good afternoon. How can I help you?',answer:'My flight to Madrid is delayed and I have a connection there.',pron:'Maï flaït tou Ma-drid iz di-léïd and aï hav e ke-nek-cheun zère.',fr:'Mon vol pour Madrid est retardé et j’ai une correspondance là-bas.',choices:['My flight to Madrid is delayed and I have a connection there.','I need a quiet hotel room.','I would like a coffee and the bill.']},
{speaker:'Agent',text:'May I see your boarding pass?',answer:'Yes, here it is. My final destination is Dakar.',pron:'Yes, hière it iz. Maï faï-neul des-ti-néï-cheun iz Da-kar.',fr:'Oui, le voici. Ma destination finale est Dakar.',choices:['Yes, here it is. My final destination is Dakar.','My final dessert is chocolate.','My project deadline is Friday.']},
{speaker:'Agent',text:'I can see the problem. Your first flight is now two hours late.',answer:'Do you think I will miss my connection?',pron:'Dou iou sink aï ouil mis maï ke-nek-cheun?',fr:'Pensez-vous que je vais rater ma correspondance ?',choices:['Do you think I will miss my connection?','Do you think breakfast is included?','Do you think I need antibiotics?']},
{speaker:'Agent',text:'Unfortunately, yes. The connection time will be too short.',answer:'What options do I have?',pron:'Ouat op-cheunz dou aï hav?',fr:'Quelles options ai-je ?',choices:['What options do I have?','What soup do you have?','What symptoms do I have?']},
{speaker:'Agent',text:'I can rebook you on a later flight to Dakar tonight.',answer:'What time would that flight leave Madrid?',pron:'Ouat taïm woud zat flaït liiv Ma-drid?',fr:'À quelle heure ce vol quitterait-il Madrid ?',choices:['What time would that flight leave Madrid?','What time is hotel breakfast?','What time is the meeting?']},
{speaker:'Agent',text:'It leaves at eleven forty-five tonight.',answer:'Would I have enough time to make that connection?',pron:'Woud aï hav i-neuf taïm tou méïk zat ke-nek-cheun?',fr:'Aurais-je suffisamment de temps pour prendre cette correspondance ?',choices:['Would I have enough time to make that connection?','Would I have enough vegetables?','Would I have enough medicine?']},
{speaker:'Agent',text:'Yes, you would have about two and a half hours in Madrid.',answer:'Okay. Please rebook me on that flight.',pron:'O-kéï. Pliiz ri-bouk mi on zat flaït.',fr:'D’accord. Merci de me réserver sur ce vol.',choices:['Okay. Please rebook me on that flight.','Please book me a restaurant table.','Please change my doctor.']},
{speaker:'Agent',text:'Done. Your new boarding pass is being printed now.',answer:'Thank you. Will my checked luggage be transferred automatically?',pron:'Sènk iou. Ouil maï tchekt leu-guidj bi trans-feurd o-to-ma-ti-kli?',fr:'Merci. Mes bagages enregistrés seront-ils transférés automatiquement ?',choices:['Thank you. Will my checked luggage be transferred automatically?','Will my lunch be transferred?','Will my report be transferred to the hotel?']},
{speaker:'Agent',text:'Yes, your luggage will be sent to your final destination.',answer:'That is good to know. Is there a meal voucher because of the delay?',pron:'Zat iz goud tou no. Iz zère e miil vaou-tcheur bi-koz ov ze di-léï?',fr:'C’est bon à savoir. Y a-t-il un bon repas à cause du retard ?',choices:['That is good to know. Is there a meal voucher because of the delay?','Is there a prescription because of the delay?','Is there a meeting because of the delay?']},
{speaker:'Agent',text:'Yes. Because the delay is over two hours, you can receive a food voucher.',answer:'Where can I collect it?',pron:'Ouère kan aï ke-lekt it?',fr:'Où puis-je le récupérer ?',choices:['Where can I collect it?','Where can I see the doctor?','Where can I finish the report?']},
{speaker:'Agent',text:'At the customer service desk near gate twenty.',answer:'Thanks. Will the gate for my first flight stay the same?',pron:'Sènks. Ouil ze géït for maï feurst flaït stéï ze séïm?',fr:'Merci. La porte de mon premier vol restera-t-elle la même ?',choices:['Thanks. Will the gate for my first flight stay the same?','Will the hotel room stay the same?','Will the menu stay the same?']},
{speaker:'Agent',text:'For now, yes, but please check the screens regularly.',answer:'I will. Thank you for helping me sort this out.',pron:'Aï ouil. Sènk iou for help-ing mi sort zis aout.',fr:'Je le ferai. Merci de m’avoir aidé à régler cela.',choices:['I will. Thank you for helping me sort this out.','I will. Please bring the fish.','I will. The meeting is cancelled.']}
]},
{
id:'neighbour',icon:'🏠',title:'Parler avec un voisin',place:'Discussion devant la maison',level:'A2–B1',duration:'3–4 min',goal:'Faire connaissance, parler du quartier et organiser un service entre voisins.',
vocab:{neighbourhood:{fr:'quartier',pron:'néï-beur-houd'},recently:{fr:'récemment',pron:'rii-seunt-li'},nearby:{fr:'à proximité',pron:'nièr-baï'},recommend:{fr:'recommander',pron:'re-keu-mend'},bin:{fr:'poubelle',pron:'bin'},delivery:{fr:'livraison',pron:'di-li-ve-ri'},favour:{fr:'service',pron:'féï-veur'},appreciate:{fr:'apprécier',pron:'e-pri-chi-éït'}},
steps:[
{speaker:'Neighbour',text:'Hi. I do not think we have met before. I am Daniel from number twelve.',answer:'Nice to meet you, Daniel. I am Cheikh. I moved in recently.',pron:'Naïs tou miit iou, Da-nieul. Aï am Cheikh. Aï mouvd in rii-seunt-li.',fr:'Enchanté Daniel. Je suis Cheikh. J’ai emménagé récemment.',choices:['Nice to meet you, Daniel. I am Cheikh. I moved in recently.','I would like a table for two.','My flight is delayed.']},
{speaker:'Neighbour',text:'Welcome to the neighbourhood. How are you finding it so far?',answer:'I like it. It seems quiet and friendly.',pron:'Aï laïk it. It siimz kwaï-eut and frend-li.',fr:'Ça me plaît. Cela semble calme et convivial.',choices:['I like it. It seems quiet and friendly.','The fish is excellent.','My throat hurts.']},
{speaker:'Neighbour',text:'It is usually very quiet. Do you have children?',answer:'Yes, I have children, so a quiet area is important for us.',pron:'Yes, aï hav tchil-dren, so e kwaï-eut é-ri-a iz im-por-teunt for eus.',fr:'Oui, j’ai des enfants, donc un quartier calme est important pour nous.',choices:['Yes, I have children, so a quiet area is important for us.','Yes, I have two boarding passes.','Yes, I have a project deadline.']},
{speaker:'Neighbour',text:'There is a good park nearby, about ten minutes on foot.',answer:'That sounds useful. Is there a supermarket nearby too?',pron:'Zat saounds ious-feul. Iz zère e sou-peur-mar-kit nièr-baï tou?',fr:'Ça a l’air pratique. Y a-t-il aussi un supermarché à proximité ?',choices:['That sounds useful. Is there a supermarket nearby too?','Is there a doctor on the plane?','Is breakfast included too?']},
{speaker:'Neighbour',text:'Yes, there is one next to the post office. It stays open until nine.',answer:'Great. Can you recommend a good bakery?',pron:'Gréït. Kan iou re-keu-mend e goud béï-keu-ri?',fr:'Super. Pouvez-vous recommander une bonne boulangerie ?',choices:['Great. Can you recommend a good bakery?','Can you recommend a prescription?','Can you recommend a flight delay?']},
{speaker:'Neighbour',text:'There is an excellent bakery on King Street.',answer:'Thanks. I will try it this weekend.',pron:'Sènks. Aï ouil traï it zis wiik-end.',fr:'Merci. Je vais l’essayer ce week-end.',choices:['Thanks. I will try it this weekend.','I will check out at eleven.','I will send the report Friday.']},
{speaker:'Neighbour',text:'By the way, bin collection is every Thursday morning.',answer:'Good to know. Should I put the bins out on Wednesday evening?',pron:'Goud tou no. Choud aï pout ze bins aout on Wenz-déï iiv-ning?',fr:'Bon à savoir. Dois-je sortir les poubelles mercredi soir ?',choices:['Good to know. Should I put the bins out on Wednesday evening?','Should I rebook the bins?','Should I order the bins as dessert?']},
{speaker:'Neighbour',text:'Yes, that is what most people do.',answer:'Perfect. Thanks for the advice.',pron:'Peu-fect. Sènks for ze e-dvaïs.',fr:'Parfait. Merci pour le conseil.',choices:['Perfect. Thanks for the advice.','Perfect. Bring my passport.','Perfect. I need antibiotics.']},
{speaker:'Neighbour',text:'Could I ask you a small favour for tomorrow?',answer:'Of course. What do you need?',pron:'Ov cors. Ouat dou iou niid?',fr:'Bien sûr. De quoi avez-vous besoin ?',choices:['Of course. What do you need?','What do you recommend as a main course?','What gate is my flight?']},
{speaker:'Neighbour',text:'I am expecting a delivery, but I will be at work. Could you take it for me?',answer:'Yes, no problem. I should be home in the afternoon.',pron:'Yes, no pro-blem. Aï choud bi hom in zi af-teur-noun.',fr:'Oui, pas de problème. Je devrais être chez moi l’après-midi.',choices:['Yes, no problem. I should be home in the afternoon.','I should be at the airport.','I should pay the bill.']},
{speaker:'Neighbour',text:'That would really help. I can collect it from you in the evening.',answer:'That is fine. Just knock on the door when you get back.',pron:'Zat iz faïne. Djeust nok on ze dor wen iou get bak.',fr:'Ça marche. Frappez simplement à la porte quand vous rentrez.',choices:['That is fine. Just knock on the door when you get back.','Just call the doctor for dessert.','Just rebook my project.']},
{speaker:'Neighbour',text:'Thanks, I really appreciate it. And if you ever need anything, let me know.',answer:'Thank you. It is nice to have helpful neighbours.',pron:'Sènk iou. It iz naïs tou hav help-feul néï-beurz.',fr:'Merci. C’est agréable d’avoir des voisins serviables.',choices:['Thank you. It is nice to have helpful neighbours.','The delay is two hours.','I am allergic to peanuts.']}
]}
];
window.ADULT_TRAINING=[
{type:'response',title:'Au travail',prompt:'Your manager says: “Can you send me the report before five?”',choices:['Yes, I will send it before five.','Yes, I sent tomorrow.','I am report before five.'],answer:0,explain:'Pour une promesse simple : “I will + verbe”.',pron:'Yes, aï ouil send it bi-for faïv.'},
{type:'response',title:'Restaurant',prompt:'The waiter asks: “Would you like anything else?”',choices:['No, thank you. Could I have the bill, please?','I am bill please.','I have anything yesterday.'],answer:0,explain:'“Could I have…?” est naturel et poli.',pron:'No, sènk iou. Koud aï hav ze bil, pliiz?'},
{type:'response',title:'Aéroport',prompt:'Your flight is delayed. Ask about your connection.',choices:['Will I still make my connection?','Where my connection is make?','Connection have late?'],answer:0,explain:'“Will I still make…?” = est-ce que je pourrai quand même prendre… ?',pron:'Ouil aï stil méïk maï ke-nek-cheun?'},
{type:'response',title:'Médecin',prompt:'The doctor asks: “How long have you had this pain?”',choices:['I have had it for three days.','I have it since three days.','I am pain three days.'],answer:0,explain:'Avec une durée jusqu’à maintenant : “for three days”.',pron:'Aï hav had it for sri déïz.'},
{type:'response',title:'Hôtel',prompt:'You want a quieter room.',choices:['Is there a quieter room available?','Have you quiet room more?','I want silence room.'],answer:0,explain:'Comparatif naturel : “a quieter room”.',pron:'Iz zère e kwaï-eu-teur roum e-véï-le-beul?'},
{type:'response',title:'Voisinage',prompt:'Your neighbour asks for a small favour.',choices:['Of course. What do you need?','I am favour.','What you needing?'],answer:0,explain:'Réponse courte, naturelle et très utilisée.',pron:'Ov cors. Ouat dou iou niid?'},
{type:'meaning',title:'Vocabulaire',prompt:'Que signifie “deadline” ?',choices:['date limite','retard','réunion'],answer:0,explain:'Deadline = date limite à respecter.',pron:'ded-laïne'},
{type:'meaning',title:'Vocabulaire',prompt:'Que signifie “available” ?',choices:['disponible','annulé','dangereux'],answer:0,explain:'Available = disponible / libre.',pron:'e-véï-le-beul'},
{type:'meaning',title:'Vocabulaire',prompt:'Que signifie “receipt” ?',choices:['reçu / ticket','recette de cuisine','réception'],answer:0,explain:'Receipt = reçu / ticket de caisse.',pron:'ri-siit'},
{type:'meaning',title:'Vocabulaire',prompt:'Que signifie “instead” ?',choices:['à la place','en retard','pourtant'],answer:0,explain:'Instead = à la place / plutôt.',pron:'in-sted'},
{type:'response',title:'Téléphone professionnel',prompt:'Someone asks to speak to a colleague who is unavailable.',choices:['She is not available right now. Can I take a message?','She no here. Speak later.','You message she.'],answer:0,explain:'Formule professionnelle : “Can I take a message?”',pron:'Chi iz not e-véï-le-beul raït naou. Kan aï téïk e me-sidj?'},
{type:'response',title:'Demander de répéter',prompt:'You did not understand what someone said.',choices:['Sorry, could you say that again more slowly?','Repeat you slow.','I not understand speaking.'],answer:0,explain:'Formule polie et naturelle pour A2–B1.',pron:'So-ri, koud iou séï zat e-guèn mor slo-li?'}
];