(() => {
const scenarios=window.ADULT_ORAL_SCENARIOS||[];
const grid=document.getElementById('oralScenarioGrid'),count=document.getElementById('oralCount'),levelSel=document.getElementById('oralLevel'),catSel=document.getElementById('oralCategory'),search=document.getElementById('oralSearch');
const picker=document.getElementById('oralPicker'),session=document.getElementById('oralSession');
const npcText=document.getElementById('npcText'),counterpartLabel=document.getElementById('counterpartLabel'),mic=document.getElementById('oralMic'),listenState=document.getElementById('listenState'),transcriptCard=document.getElementById('transcriptCard'),transcriptText=document.getElementById('transcriptText'),coachCard=document.getElementById('coachCard'),coachScore=document.getElementById('coachScore'),coachEnglish=document.getElementById('coachEnglish'),coachPron=document.getElementById('coachPron'),coachFrench=document.getElementById('coachFrench'),progressFill=document.getElementById('oralProgressFill'),stepLabel=document.getElementById('oralStep'),scoreLabel=document.getElementById('oralScore'),handsFree=document.getElementById('handsFree');
let current=null,turnIndex=0,scores=[],waitingSpeech=false,lastNpc='',activeWord=null,autoMicRequested=false,ttsToken=0;
const esc=s=>String(s||'').replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[c]));
const norm=s=>String(s||'').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9' ]/g,' ').replace(/\s+/g,' ').trim();
function handleTtsFinished(token=ttsToken){if(token!==ttsToken)return;mic.disabled=false;if(autoMicRequested&&!waitingSpeech){autoMicRequested=false;setTimeout(()=>{if(current&&!waitingSpeech)startListening()},90)}}
function speak(text,rate=.8){const token=++ttsToken;try{if(window.AndroidTTS&&AndroidTTS.speak){AndroidTTS.speak(text,rate);return token}}catch(e){}if('speechSynthesis'in window){const u=new SpeechSynthesisUtterance(text);u.lang='en-GB';u.rate=rate;u.onend=()=>handleTtsFinished(token);u.onerror=()=>handleTtsFinished(token);speechSynthesis.cancel();speechSynthesis.speak(u)}else handleTtsFinished(token);return token}
function preload(text,rate=.78){if(!text)return;try{if(window.AndroidTTS&&AndroidTTS.preload)AndroidTTS.preload(text,rate)}catch(e){}}
window.onNativeTtsFinished=()=>handleTtsFinished(ttsToken);
function categories(){[...new Set(scenarios.map(s=>s.category))].sort().forEach(c=>catSel.insertAdjacentHTML('beforeend',`<option value="${esc(c)}">${esc(c)}</option>`))}
function filtered(){const q=norm(search.value),lev=levelSel.value,cat=catSel.value;return scenarios.filter(s=>(lev==='all'||s.level===lev)&&(cat==='all'||s.category===cat)&&(!q||norm(`${s.title} ${s.category} ${s.goal}`).includes(q)))}
function render(){const arr=filtered();count.textContent=`${arr.length} situation${arr.length>1?'s':''}`;grid.innerHTML=arr.map(s=>`<button class="oralScenario" data-id="${esc(s.id)}"><span class="icon">${s.icon}</span><h3>${esc(s.title)}</h3><p>${esc(s.goal)}</p><div class="scenarioMeta"><span>${esc(s.levelLabel)}</span><span>${esc(s.duration)}</span></div></button>`).join('');grid.querySelectorAll('[data-id]').forEach(b=>b.onclick=()=>startScenario(scenarios.find(s=>s.id===b.dataset.id)))}
[levelSel,catSel].forEach(el=>el.onchange=render);search.oninput=render;document.getElementById('randomOral').onclick=()=>{const a=filtered();if(a.length)startScenario(a[Math.floor(Math.random()*a.length)])};
function markVocab(text){let out=esc(text);Object.entries(current?.vocab||{}).sort((a,b)=>b[0].length-a[0].length).forEach(([word])=>{const r=new RegExp(`\\b${word.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')}\\b`,'gi');out=out.replace(r,m=>`<span class="newWord" data-word="${esc(word)}">${m}</span>`)});return out}
function bindWords(root){root.querySelectorAll('.newWord').forEach(el=>el.onclick=e=>{e.stopPropagation();const word=el.dataset.word,meta=current.vocab[word];activeWord=word;document.getElementById('wordTitle').textContent=word;document.getElementById('wordMeaning').textContent=meta.fr;document.getElementById('wordPron').textContent=`Prononciation : ${meta.pron}`;document.getElementById('wordSheet').classList.add('open');const learned=new Set(JSON.parse(localStorage.getItem('adultWords')||'[]'));learned.add(word);localStorage.setItem('adultWords',JSON.stringify([...learned]))})}
function startScenario(s){current=s;turnIndex=0;scores=[];waitingSpeech=false;autoMicRequested=false;picker.hidden=true;session.hidden=false;document.getElementById('oralHead').innerHTML=`<section class="hero"><span class="levelBadge">${esc(s.levelLabel)} • ${esc(s.duration)}</span><h2>${s.icon} ${esc(s.title)}</h2><p>${esc(s.goal)}</p><small>Interlocuteur : ${esc(s.counterpart)}</small></section>`;if(s.turns[0])preload(s.turns[0].npc,.78);renderTurn();window.scrollTo({top:0,behavior:'smooth'})}
function renderTurn(){if(!current)return;if(turnIndex>=current.turns.length){finish();return}const t=current.turns[turnIndex];counterpartLabel.textContent=current.counterpart;npcText.innerHTML=markVocab(t.npc);bindWords(npcText);lastNpc=t.npc;stepLabel.textContent=`Échange ${turnIndex+1}/${current.turns.length}`;progressFill.style.width=`${(turnIndex/current.turns.length)*100}%`;scoreLabel.textContent=scores.length?`${Math.round(scores.reduce((a,b)=>a+b,0)/scores.length)}%`:'—';transcriptCard.hidden=true;coachCard.hidden=true;listenState.textContent='Écoute puis réponds naturellement en anglais.';mic.classList.remove('listening');mic.disabled=true;autoMicRequested=handsFree.checked;speak(t.npc,.78);const next=current.turns[turnIndex+1];if(next)preload(next.npc,.78);preload(t.expected,.68)}
function startListening(){if(waitingSpeech)return;autoMicRequested=false;waitingSpeech=true;mic.disabled=false;mic.classList.add('listening');listenState.textContent='🎙️ Je t’écoute… parle maintenant.';try{if(window.AndroidSpeech&&AndroidSpeech.startRecognition){AndroidSpeech.startRecognition('en-GB');return}}catch(e){}const SR=window.SpeechRecognition||window.webkitSpeechRecognition;if(SR){const r=new SR();r.lang='en-GB';r.interimResults=false;r.maxAlternatives=3;r.onresult=e=>handleSpeech(e.results[0][0].transcript);r.onerror=()=>speechError('Je n’ai pas compris. Réessaie.');r.start()}else speechError('Reconnaissance vocale indisponible sur ce navigateur.')}
mic.onclick=()=>{if(!mic.disabled)startListening()};
function keywords(s){const stop=new Set('i you he she it we they a an the to of for and is are am be do does did have has had would could should please my your our this that there here in on at with from me very just some one now today'.split(' '));return norm(s).split(' ').filter(w=>w.length>2&&!stop.has(w))}
function similarity(spoken,target){const a=norm(spoken),b=norm(target);if(!a)return 0;const ka=keywords(a),kb=keywords(b);const matched=kb.filter(k=>ka.some(x=>x===k||x.startsWith(k.slice(0,Math.max(3,k.length-2)))||k.startsWith(x.slice(0,Math.max(3,x.length-2))))).length;const keyScore=kb.length?matched/kb.length:0;const aw=new Set(a.split(' ')),bw=b.split(' '),overlap=bw.filter(w=>aw.has(w)).length/Math.max(1,bw.length);const lengthScore=Math.min(1,a.split(' ').length/Math.max(4,b.split(' ').length*.65));return Math.round((keyScore*.55+overlap*.3+lengthScore*.15)*100)}
function handleSpeech(text){waitingSpeech=false;mic.classList.remove('listening');const t=current.turns[turnIndex],score=similarity(text,t.expected);scores.push(score);transcriptText.textContent=text||'—';transcriptCard.hidden=false;coachCard.hidden=false;coachScore.textContent=score>=75?`✅ ${score}% • Très naturel`:score>=50?`👍 ${score}% • Bonne réponse`:`💡 ${score}% • À améliorer`;coachScore.className='coachScore '+(score>=75?'good':score>=50?'mid':'low');coachEnglish.innerHTML=markVocab(t.expected);bindWords(coachEnglish);coachPron.textContent=`Prononciation : ${t.pron}`;coachFrench.textContent=t.fr;listenState.textContent=score>=50?'Réponse comprise. Compare avec la formulation proposée.':'Ta réponse a été entendue. Utilise la proposition pour progresser.';mic.disabled=true;localStorage.setItem('adultOralLastTranscript',text);const next=current.turns[turnIndex+1];if(next)preload(next.npc,.78)}
function speechError(msg){waitingSpeech=false;mic.classList.remove('listening');listenState.textContent=msg;mic.disabled=false}
window.onNativeSpeechResult=handleSpeech;window.onNativeSpeechError=speechError;
document.getElementById('replayNpc').onclick=()=>{autoMicRequested=false;mic.disabled=true;speak(lastNpc,.72)};document.getElementById('hearCoach').onclick=()=>{autoMicRequested=false;mic.disabled=true;current&&speak(current.turns[turnIndex].expected,.68)};document.getElementById('continueOral').onclick=()=>{turnIndex++;renderTurn()};
function finish(){const avg=scores.length?Math.round(scores.reduce((a,b)=>a+b,0)/scores.length):0;progressFill.style.width='100%';const xp=Math.max(20,Math.round(avg/2)+current.rank*10);localStorage.setItem('adultXp',Number(localStorage.getItem('adultXp')||0)+xp);localStorage.setItem('adultDone',Number(localStorage.getItem('adultDone')||0)+1);session.innerHTML=`<section class="hero finishOral"><div class="eyebrow">Discussion terminée</div><h2>${current.icon} ${esc(current.title)}</h2><div class="scoreBig">${avg}%</div><p>Score oral moyen • +${xp} XP adulte</p><p>${avg>=75?'Tu peux refaire cette situation en mode mains libres ou passer au niveau supérieur.':avg>=50?'Bonne base. Refais-la une fois pour rendre tes réponses plus naturelles.':'Réécoute les propositions puis rejoue la scène.'}</p><a class="modeCard" href="adult-oral.html"><span class="icon">🎙️</span><span><strong>Choisir une autre situation</strong><small>160 situations disponibles.</small></span><span class="arrow">›</span></a></section>`}
document.getElementById('closeWord').onclick=()=>document.getElementById('wordSheet').classList.remove('open');document.getElementById('wordAudio').onclick=()=>activeWord&&speak(activeWord,.65);document.getElementById('wordSheet').onclick=e=>{if(e.target.id==='wordSheet')e.currentTarget.classList.remove('open')};
categories();render();
})();