(() => {
'use strict';
const $=id=>document.getElementById(id), scenarios=window.ADULT_ORAL_SCENARIOS||[];
const audio=window.LearningAudio, store=window.LearningStore, esc=s=>String(s||'').replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));
let current=null, turnIndex=0, scores=[], waiting=false, completed=false, token=0, recognizer=null, micTimer=null, visible=24;
function save(){if(current&&!completed)store.saveSession('adultOral',{id:current.id,turnIndex,scores});}
function cancelMic(){waiting=false;clearTimeout(micTimer);try{window.AndroidSpeech?.cancelRecognition?.();recognizer?.abort();}catch(_){}recognizer=null;$('oralMic').classList.remove('listening');}
function stop(){token++;audio.stop();cancelMic();}
function filtered(){const q=SpeechEvaluation.normalize($('oralSearch').value);return scenarios.filter(s=>($('oralLevel').value==='all'||s.level===$('oralLevel').value)&&($('oralCategory').value==='all'||s.category===$('oralCategory').value)&&(!q||SpeechEvaluation.normalize(s.title+' '+s.goal+' '+s.category).includes(q)));}
function renderList(){const list=filtered();$('oralCount').textContent=list.length+' situations';$('oralScenarioGrid').innerHTML=list.slice(0,visible).map(s=>`<button class="oralScenario" data-id="${s.id}"><span class="icon">${s.icon}</span><h3>${esc(s.title)}</h3><p>${esc(s.goal)}</p><div class="scenarioMeta"><span>${esc(s.levelLabel)}</span><span>${esc(s.duration)}</span></div></button>`).join('')||( '<p>Aucune situation trouvée. Essaie un autre mot.</p>');$('oralMore').hidden=visible>=list.length;}
$('oralScenarioGrid').onclick=e=>{const b=e.target.closest('[data-id]');if(b)start(scenarios.find(s=>s.id===b.dataset.id));};
function vocab(text){const fragment=document.createDocumentFragment(),words=Object.keys(current.vocab||{}).sort((a,b)=>b.length-a.length);if(!words.length){fragment.append(text);return fragment;}const re=new RegExp('\\b('+words.map(x=>x.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')).join('|')+')\\b','gi');let previous=0;for(const m of text.matchAll(re)){fragment.append(text.slice(previous,m.index));const b=document.createElement('button');b.className='newWord';b.textContent=m[0];b.onclick=()=>openWord(words.find(w=>w.toLowerCase()===m[0].toLowerCase()));fragment.append(b);previous=m.index+m[0].length;}fragment.append(text.slice(previous));return fragment;}
function openWord(word){const meta=current.vocab[word];$('wordTitle').textContent=word;$('wordMeaning').textContent=meta.fr;$('wordPron').textContent='Écoute puis répète le mot.';$('wordSheet').classList.add('open');$('wordAudio').onclick=()=>audio.speak(word,.62);const previous=store.read('adultWords',[]),learned=new Set(Array.isArray(previous)?previous:[]);learned.add(word);store.write('adultWords',[...learned]);}
async function read(text,rate=.78,auto=false){cancelMic();const request=++token;$('oralMic').disabled=true;$('listenState').textContent='Préparation de la voix…';const result=await audio.speak(text,rate);if(request!==token||completed)return;$('oralMic').disabled=false;if(result==='error')$('listenState').textContent='Voix indisponible. Tu peux lire et écrire ta réponse.';else $('listenState').textContent='À toi. Réponds au micro ou écris ta réponse.';if(auto&&result==='done')startListening();}
function start(s,resume){if(!s)return;stop();current=s;completed=false;turnIndex=resume?Math.max(0,Math.min(s.turns.length-1,Number(resume.turnIndex)||0)):0;scores=resume&&Array.isArray(resume.scores)?resume.scores.slice(0,s.turns.length):[];$('oralPicker').hidden=true;$('oralSession').hidden=false;$('oralHead').innerHTML=`<section class="hero"><span class="levelBadge">${esc(s.levelLabel)}</span><h2>${s.icon} ${esc(s.title)}</h2><p>${esc(s.goal)}</p><button id="changeOral" class="secondary">Changer de situation</button></section>`;$('changeOral').onclick=()=>{save();stop();$('oralSession').hidden=true;$('oralPicker').hidden=false;};renderTurn(false);}
function renderTurn(autoplay=true){if(turnIndex>=current.turns.length){finish();return;}stop();const t=current.turns[turnIndex];$('npcText').replaceChildren(vocab(t.npc));$('counterpartLabel').textContent=current.counterpart;$('oralStep').textContent=`Échange ${turnIndex+1}/${current.turns.length}`;$('oralProgressFill').style.width=100*turnIndex/current.turns.length+'%';const rated=scores.filter(Number.isFinite);$('oralScore').textContent=rated.length?Math.round(rated.reduce((a,b)=>a+b,0)/rated.length)+'% proximité':'—';$('transcriptCard').hidden=true;$('coachCard').hidden=true;$('oralTyped').value='';$('oralMic').disabled=false;$('listenState').textContent='Écoute la question, puis réponds au micro ou au clavier.';save();if(autoplay)read(t.npc,.78,$('handsFree').checked);else read(t.npc,.78,false);const next=current.turns[turnIndex+1];if(next)audio.preload(next.npc,.78);}
function fail(message){cancelMic();$('listenState').textContent=message;$('oralMic').disabled=false;}
function startListening(){if(!current||completed)return;if(waiting){fail('Écoute arrêtée. Tu peux réessayer.');return;}audio.stop();waiting=true;const request=++token;$('oralMic').classList.add('listening');$('listenState').textContent='Préparation du micro…';micTimer=setTimeout(()=>{if(waiting&&token===request)fail('Le micro ne répond pas. Réessaie ou écris ta réponse.');},20000);try{if(window.AndroidSpeech?.startRecognition){AndroidSpeech.startRecognition('en-GB');return;}const SR=window.SpeechRecognition||window.webkitSpeechRecognition;if(!SR){fail('Micro indisponible ici. Utilise la réponse écrite.');return;}recognizer=new SR();recognizer.lang='en-GB';recognizer.onstart=()=>{if(request===token)$('listenState').textContent='Je t’écoute… touche le micro pour arrêter.';};recognizer.onresult=e=>{if(request===token)answer(e.results[0][0].transcript);};recognizer.onerror=()=>{if(request===token)fail('Parole non reconnue. Réessaie ou écris ta réponse.');};recognizer.onend=()=>{if(request===token&&waiting)fail('Aucune réponse reconnue. Réessaie.');};recognizer.start();}catch(_){fail('Micro indisponible. Utilise la réponse écrite.');}}
function answer(text){if(!current||completed||!String(text).trim())return;cancelMic();token++;audio.stop();const t=current.turns[turnIndex],result=SpeechEvaluation.evaluate(text,t);scores[turnIndex]=result.score;$('transcriptText').textContent=text;$('transcriptCard').hidden=false;$('coachCard').hidden=false;$('coachScore').textContent=result.accepted?'✓ Formulation prévue reconnue':result.score+'% de proximité textuelle';$('coachScore').className='coachScore '+(result.accepted?'good':'mid');$('coachEnglish').replaceChildren(vocab(t.expected));$('coachFrench').textContent=t.fr;$('coachPron').textContent=result.reason;$('listenState').textContent='Compare le sens, puis réessaie ou continue.';store.write('adultOralLastTranscript',text);save();}
function finish(){stop();if(completed)return;completed=true;const valid=scores.filter(Number.isFinite),avg=valid.length?Math.round(valid.reduce((a,b)=>a+b,0)/valid.length):0;const award=store.markActivity('oral:'+current.id,1);if(award){store.write('adultXp',(Number(localStorage.getItem('adultXp'))||0)+Math.max(10,Math.round(avg/2)));store.write('adultDone',(Number(localStorage.getItem('adultDone'))||0)+1);}store.clearSession('adultOral');$('oralProgressFill').style.width='100%';$('oralSession').innerHTML=`<section class="hero"><h2>Discussion terminée</h2><p>${avg}% de proximité moyenne avec les formulations proposées.</p><p>Ce résultat compare le texte reconnu ; il ne mesure pas ton accent.</p><a class="resumeLearning" href="adult-oral.html">Choisir une autre situation</a></section>`;}
window.onNativeSpeechResult=text=>{if(waiting)answer(text);};window.onNativeSpeechError=message=>{if(waiting)fail(message);};window.onNativeSpeechState=state=>{if(waiting)$('listenState').textContent=state==='listening'?'Je t’écoute… touche le micro pour arrêter.':'Analyse de ta réponse…';};
$('oralMic').onclick=startListening;$('submitTyped').onclick=()=>answer($('oralTyped').value);$('oralTyped').onkeydown=e=>{if(e.key==='Enter')answer(e.target.value);};$('retryOral').onclick=()=>{stop();$('coachCard').hidden=true;$('transcriptCard').hidden=true;$('listenState').textContent='À toi de réessayer.';};$('replayNpc').onclick=()=>read(current.turns[turnIndex].npc,.72);$('hearCoach').onclick=()=>read(current.turns[turnIndex].expected,.62);$('continueOral').onclick=()=>{turnIndex++;renderTurn();};$('closeWord').onclick=()=>{$('wordSheet').classList.remove('open');};$('wordSheet').onclick=e=>{if(e.target.id==='wordSheet')e.target.classList.remove('open');};
[...new Set(scenarios.map(s=>s.category))].sort().forEach(c=>{const option=document.createElement('option');option.value=c;option.textContent=c;$('oralCategory').appendChild(option);});
['oralLevel','oralCategory'].forEach(id=>$(id).onchange=()=>{visible=24;renderList();});$('oralSearch').oninput=()=>{visible=24;renderList();};$('oralMore').onclick=()=>{visible+=24;renderList();};$('randomOral').onclick=()=>{const list=filtered();if(list.length)start(list[Math.floor(Math.random()*list.length)]);};
window.addEventListener('pagehide',()=>{save();stop();});window.addEventListener('learning-interrupted',()=>{save();stop();if(current&&!completed)$('listenState').textContent='Séance en pause. Réécoute la question pour reprendre.';});
renderList();const saved=store.getSession('adultOral');if(new URLSearchParams(location.search).has('resume')&&saved)start(scenarios.find(s=>s.id===saved.id),saved);
})();
