(() => {
  const $=id=>document.getElementById(id),esc=s=>String(s??'').replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[c]));
  const speak=(text,rate=.82)=>{try{if(window.AndroidTTS&&AndroidTTS.speak){AndroidTTS.speak(String(text),Number(rate));return}}catch(e){}if('speechSynthesis'in window){const u=new SpeechSynthesisUtterance(String(text));u.lang='en-US';u.rate=rate;speechSynthesis.cancel();speechSynthesis.speak(u)}};
  document.querySelectorAll('.tab').forEach(b=>b.onclick=()=>{document.querySelectorAll('.tab').forEach(x=>x.classList.toggle('active',x===b));document.querySelectorAll('.panel').forEach(p=>p.classList.toggle('active',p.id===`panel-${b.dataset.tab}`))});

  const small=['zero','one','two','three','four','five','six','seven','eight','nine','ten','eleven','twelve','thirteen','fourteen','fifteen','sixteen','seventeen','eighteen','nineteen'];
  const tens=['','','twenty','thirty','forty','fifty','sixty','seventy','eighty','ninety'];
  function numberToEnglish(n){n=Math.trunc(Number(n));if(!Number.isFinite(n))return'';if(n<0)return'minus '+numberToEnglish(-n);if(n<20)return small[n];if(n<100)return tens[Math.floor(n/10)]+(n%10?'-'+small[n%10]:'');if(n<1000)return small[Math.floor(n/100)]+' hundred'+(n%100?' and '+numberToEnglish(n%100):'');if(n<1e6)return numberToEnglish(Math.floor(n/1000))+' thousand'+(n%1000?(n%1000<100?' and ':' ')+numberToEnglish(n%1000):'');if(n<1e9)return numberToEnglish(Math.floor(n/1e6))+' million'+(n%1e6?' '+numberToEnglish(n%1e6):'');if(n<1e12)return numberToEnglish(Math.floor(n/1e9))+' billion'+(n%1e9?' '+numberToEnglish(n%1e9):'');return String(n)}
  const essentials=[0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,30,40,50,60,70,80,90,100,101,125,200,500,1000,1982,2000,2026,10000,100000,1000000];
  $('numberGrid').innerHTML=essentials.map(n=>`<article class="card numberCard"><strong>${n.toLocaleString('fr-FR')}</strong><b>${esc(numberToEnglish(n))}</b><span>${n<20?'nombre de base':n<100?'dizaine / composé':n<1000?'centaines':n<1000000?'milliers':'grand nombre'}</span><br><button class="listen numSpeak" data-t="${esc(numberToEnglish(n))}">🔊</button></article>`).join('');
  document.querySelectorAll('.numSpeak').forEach(b=>b.onclick=()=>speak(b.dataset.t));
  let lastNumberText='';$('convertNumber').onclick=()=>{const raw=$('numberInput').value.replace(/\s/g,'').replace(',','.'),n=Number(raw);if(!Number.isFinite(n)||Math.abs(n)>=1e12){$('numberEn').textContent='Nombre non pris en charge';$('numberFr').textContent='Utilise un entier inférieur à mille milliards.';$('numberResult').classList.add('show');return}lastNumberText=numberToEnglish(n);$('numberEn').textContent=lastNumberText;$('numberFr').textContent=`${Number(n).toLocaleString('fr-FR')} en anglais`;$('numberResult').classList.add('show')};$('numberSpeak').onclick=()=>lastNumberText&&speak(lastNumberText);

  function timeWords(h,m){h=((h%24)+24)%24;m=((m%60)+60)%60;const hh=h%12||12,next=(hh%12)+1;if(m===0)return `It's ${numberToEnglish(hh)} o'clock.`;if(m===15)return `It's quarter past ${numberToEnglish(hh)}.`;if(m===30)return `It's half past ${numberToEnglish(hh)}.`;if(m===45)return `It's quarter to ${numberToEnglish(next)}.`;if(m<30)return `It's ${numberToEnglish(m)} past ${numberToEnglish(hh)}.`;return `It's ${numberToEnglish(60-m)} to ${numberToEnglish(next)}.`}
  function timeFrench(h,m){const hh=String(h).padStart(2,'0'),mm=String(m).padStart(2,'0');return `${hh}:${mm}`}
  function clockSvg(h,m){const cx=100,cy=100,r=82;let marks='';for(let i=0;i<12;i++){const a=(i*30-90)*Math.PI/180,x=100+Math.cos(a)*68,y=100+Math.sin(a)*68;marks+=`<text x="${x.toFixed(1)}" y="${(y+5).toFixed(1)}" text-anchor="middle" fill="#f7fbfb" font-size="14" font-weight="700">${i===0?12:i}</text>`}const minA=(m*6-90)*Math.PI/180,hourA=((h%12)*30+m*.5-90)*Math.PI/180;const mx=100+Math.cos(minA)*58,my=100+Math.sin(minA)*58,hx=100+Math.cos(hourA)*42,hy=100+Math.sin(hourA)*42;return `<circle cx="100" cy="100" r="88" fill="#0a292d" stroke="#4a7078" stroke-width="4"/><circle cx="100" cy="100" r="82" fill="none" stroke="#23464c" stroke-width="2"/>${marks}<line x1="100" y1="100" x2="${hx.toFixed(1)}" y2="${hy.toFixed(1)}" stroke="#ffd54a" stroke-width="7" stroke-linecap="round"/><line x1="100" y1="100" x2="${mx.toFixed(1)}" y2="${my.toFixed(1)}" stroke="#22e4e4" stroke-width="4" stroke-linecap="round"/><circle cx="100" cy="100" r="6" fill="#8df000"/>`}
  const clockTimes=[[1,0],[2,30],[4,15],[7,45],[10,10],[11,55]];$('clockGrid').innerHTML=clockTimes.map(([h,m],i)=>`<article class="clockCard"><svg class="clockFace" viewBox="0 0 200 200">${clockSvg(h,m)}</svg><div class="clockText">${esc(timeWords(h,m))}</div><div class="clockFr">${timeFrench(h,m)}</div><button class="listen clockSpeak" data-h="${h}" data-m="${m}">🔊 Écouter</button></article>`).join('');document.querySelectorAll('.clockSpeak').forEach(b=>b.onclick=()=>speak(timeWords(+b.dataset.h,+b.dataset.m),.75));
  function renderLive(){const d=new Date(),h=d.getHours(),m=d.getMinutes();$('liveClock').innerHTML=clockSvg(h,m);$('liveText').textContent=timeWords(h,m);$('liveFr').textContent=timeFrench(h,m)}renderLive();setInterval(renderLive,30000);$('liveSpeak').onclick=()=>speak($('liveText').textContent,.75);
  let customText='';function showCustom(){const [h,m]=$('timeInput').value.split(':').map(Number);$('customClock').innerHTML=clockSvg(h,m);customText=timeWords(h,m);$('customText').textContent=customText;$('customFr').textContent=timeFrench(h,m);$('customClockWrap').style.display='block'}$('showTime').onclick=showCustom;$('customSpeak').onclick=()=>customText&&speak(customText,.75);showCustom();

  const dateRows=[['1st','first','premier'],['2nd','second','deuxième'],['3rd','third','troisième'],['4th','fourth','quatrième'],['10th','tenth','dixième'],['21st','twenty-first','vingt-et-unième'],['31st','thirty-first','trente-et-unième'],['1999','nineteen ninety-nine','année 1999'],['2000','two thousand','année 2000'],['2014','twenty fourteen','année 2014'],['2026','twenty twenty-six','année 2026'],['£5','five pounds','cinq livres'],['£12.50','twelve pounds fifty','douze livres cinquante'],['€20','twenty euros','vingt euros'],['$99.99','ninety-nine dollars ninety-nine','99 dollars 99']];$('dateTable').innerHTML=dateRows.map(r=>`<div class="row"><strong>${esc(r[0])}</strong><b>${esc(r[1])}</b><span class="frcol">${esc(r[2])}</span><button class="listen dateSpeak" data-t="${esc(r[1])}">🔊</button></div>`).join('');document.querySelectorAll('.dateSpeak').forEach(b=>b.onclick=()=>speak(b.dataset.t,.78));

  let qIndex=0,qScore=0,current=null;const total=10;
  function makeNumberQ(){const n=Math.floor(Math.random()*500)+1,correct=numberToEnglish(n),opts=new Set([correct]);while(opts.size<4){opts.add(numberToEnglish(Math.max(0,n+(Math.floor(Math.random()*31)-15))))}return{html:`<div class="prompt">Comment dit-on <b>${n}</b> en anglais ?</div>`,answer:correct,choices:[...opts]}}
  function makeClockQ(){const hours=[1,2,3,4,5,6,7,8,9,10,11,12],mins=[0,15,30,45,10,20,40,50],h=hours[Math.floor(Math.random()*hours.length)],m=mins[Math.floor(Math.random()*mins.length)],correct=timeWords(h,m),opts=new Set([correct]);while(opts.size<4){const oh=hours[Math.floor(Math.random()*hours.length)],om=mins[Math.floor(Math.random()*mins.length)];opts.add(timeWords(oh,om))}return{html:`<div style="text-align:center"><svg class="clockFace" viewBox="0 0 200 200">${clockSvg(h,m)}</svg><div class="prompt">Quelle heure indique cette horloge ?</div></div>`,answer:correct,choices:[...opts]}}
  function drawQuiz(){if(qIndex>=total){$('quizQuestion').innerHTML=`<div style="text-align:center"><div class="prompt">Terminé : ${qScore}/${total}</div><p class="hint">${qScore>=8?'Très bon niveau sur les nombres et l’heure.':qScore>=5?'Bon début. Revois les cartes puis recommence.':'Reviens sur les onglets Chiffres et Horloge avant un nouvel essai.'}</p><button class="action" id="restartQuiz">Recommencer</button></div>`;$('quizPos').textContent=`${total}/${total}`;$('quizFeedback').className='feedback';$('nextQuiz').style.display='none';$('restartQuiz').onclick=()=>{qIndex=0;qScore=0;drawQuiz()};return}current=Math.random()<.5?makeNumberQ():makeClockQ();$('quizPos').textContent=`${qIndex+1}/${total}`;$('quizScore').textContent=`${qScore} point${qScore>1?'s':''}`;$('quizQuestion').innerHTML=current.html+`<div class="answers">${current.choices.sort(()=>Math.random()-.5).map(c=>`<button class="answer qAns" data-v="${esc(c)}">${esc(c)}</button>`).join('')}</div>`;$('quizFeedback').className='feedback';$('nextQuiz').style.display='none';document.querySelectorAll('.qAns').forEach(b=>b.onclick=()=>{document.querySelectorAll('.qAns').forEach(x=>x.disabled=true);const ok=b.dataset.v===current.answer;b.classList.add(ok?'good':'bad');if(ok)qScore++;const f=$('quizFeedback');f.className='feedback show '+(ok?'ok':'no');f.innerHTML=ok?'✅ Correct.':`❌ Bonne réponse : <b>${esc(current.answer)}</b>`;$('quizScore').textContent=`${qScore} point${qScore>1?'s':''}`;$('nextQuiz').style.display='block'})}
  $('nextQuiz').onclick=()=>{qIndex++;drawQuiz()};drawQuiz();
})();
