window.QUIZ_PHRASES = [
  {en:"I like football",fr:"J'aime le football",level:"facile"},
  {en:"I love my family",fr:"J'aime ma famille",level:"facile"},
  {en:"I am happy",fr:"Je suis heureux",level:"facile"},
  {en:"I am tired",fr:"Je suis fatigué",level:"facile"},
  {en:"I am hungry",fr:"J'ai faim",level:"facile"},
  {en:"I am thirsty",fr:"J'ai soif",level:"facile"},
  {en:"You are my friend",fr:"Tu es mon ami",level:"facile"},
  {en:"This is my house",fr:"C'est ma maison",level:"facile"},
  {en:"The cat is small",fr:"Le chat est petit",level:"facile"},
  {en:"The dog is big",fr:"Le chien est grand",level:"facile"},
  {en:"Open the door",fr:"Ouvre la porte",level:"facile"},
  {en:"Close the window",fr:"Ferme la fenêtre",level:"facile"},
  {en:"Read the book",fr:"Lis le livre",level:"facile"},
  {en:"Write your name",fr:"Écris ton nom",level:"facile"},
  {en:"Listen carefully",fr:"Écoute attentivement",level:"facile"},
  {en:"I go to school",fr:"Je vais à l'école",level:"facile"},
  {en:"We play together",fr:"Nous jouons ensemble",level:"facile"},
  {en:"The sun is hot",fr:"Le soleil est chaud",level:"facile"},
  {en:"The water is cold",fr:"L'eau est froide",level:"facile"},
  {en:"Today is Monday",fr:"Aujourd'hui c'est lundi",level:"facile"},
  {en:"Can you help me",fr:"Peux-tu m'aider",level:"moyen"},
  {en:"Where is my book",fr:"Où est mon livre",level:"moyen"},
  {en:"What is your name",fr:"Comment tu t'appelles",level:"moyen"},
  {en:"How are you today",fr:"Comment vas-tu aujourd'hui",level:"moyen"},
  {en:"I want to learn English",fr:"Je veux apprendre l'anglais",level:"moyen"},
  {en:"My brother plays football",fr:"Mon frère joue au football",level:"moyen"},
  {en:"My mother cooks dinner",fr:"Ma mère prépare le dîner",level:"moyen"},
  {en:"My father drives the car",fr:"Mon père conduit la voiture",level:"moyen"},
  {en:"The children are at school",fr:"Les enfants sont à l'école",level:"moyen"},
  {en:"Please sit on the chair",fr:"Assieds-toi sur la chaise s'il te plaît",level:"moyen"},
  {en:"Put the book on the table",fr:"Pose le livre sur la table",level:"moyen"},
  {en:"The goalkeeper stops the ball",fr:"Le gardien arrête le ballon",level:"moyen"},
  {en:"Our team wins the match",fr:"Notre équipe gagne le match",level:"moyen"},
  {en:"I drink water after training",fr:"Je bois de l'eau après l'entraînement",level:"moyen"},
  {en:"We eat breakfast in the morning",fr:"Nous prenons le petit déjeuner le matin",level:"moyen"},
  {en:"The bird is in the garden",fr:"L'oiseau est dans le jardin",level:"moyen"},
  {en:"The teacher asks a question",fr:"Le professeur pose une question",level:"moyen"},
  {en:"The student writes the answer",fr:"L'élève écrit la réponse",level:"moyen"},
  {en:"I can speak a little English",fr:"Je peux parler un peu anglais",level:"moyen"},
  {en:"See you tomorrow morning",fr:"À demain matin",level:"moyen"}
];
