window.QUIZ_WORDS = [
  { en: "hello", fr: "bonjour", theme: "mix", level: "facile" },
  { en: "goodbye", fr: "au revoir", theme: "mix", level: "facile" },
  { en: "please", fr: "s'il te plaît", theme: "mix", level: "facile" },
  { en: "thank you", fr: "merci", theme: "mix", level: "facile" },
  { en: "yes", fr: "oui", theme: "mix", level: "facile" },
  { en: "no", fr: "non", theme: "mix", level: "facile" },
  { en: "maybe", fr: "peut-être", theme: "mix", level: "moyen" },
  { en: "sorry", fr: "désolé", theme: "mix", level: "facile" },
  { en: "good morning", fr: "bonjour le matin", theme: "mix", level: "moyen" },
  { en: "good night", fr: "bonne nuit", theme: "mix", level: "moyen" },

  { en: "one", fr: "un", theme: "mix", level: "facile" },
  { en: "two", fr: "deux", theme: "mix", level: "facile" },
  { en: "three", fr: "trois", theme: "mix", level: "facile" },
  { en: "four", fr: "quatre", theme: "mix", level: "facile" },
  { en: "five", fr: "cinq", theme: "mix", level: "facile" },
  { en: "six", fr: "six", theme: "mix", level: "facile" },
  { en: "seven", fr: "sept", theme: "mix", level: "facile" },
  { en: "eight", fr: "huit", theme: "mix", level: "facile" },
  { en: "nine", fr: "neuf", theme: "mix", level: "facile" },
  { en: "ten", fr: "dix", theme: "mix", level: "facile" },
  { en: "eleven", fr: "onze", theme: "mix", level: "moyen" },
  { en: "twelve", fr: "douze", theme: "mix", level: "moyen" },
  { en: "twenty", fr: "vingt", theme: "mix", level: "moyen" },
  { en: "hundred", fr: "cent", theme: "mix", level: "moyen" },

  { en: "red", fr: "rouge", theme: "mix", level: "facile" },
  { en: "blue", fr: "bleu", theme: "mix", level: "facile" },
  { en: "green", fr: "vert", theme: "mix", level: "facile" },
  { en: "yellow", fr: "jaune", theme: "mix", level: "facile" },
  { en: "black", fr: "noir", theme: "mix", level: "facile" },
  { en: "white", fr: "blanc", theme: "mix", level: "facile" },
  { en: "orange", fr: "orange", theme: "mix", level: "facile" },
  { en: "purple", fr: "violet", theme: "mix", level: "moyen" },
  { en: "brown", fr: "marron", theme: "mix", level: "moyen" },
  { en: "pink", fr: "rose", theme: "mix", level: "facile" },
  { en: "grey", fr: "gris", theme: "mix", level: "moyen" },
  { en: "gold", fr: "or", theme: "mix", level: "moyen" },

  { en: "father", fr: "père", theme: "mix", level: "facile" },
  { en: "mother", fr: "mère", theme: "mix", level: "facile" },
  { en: "brother", fr: "frère", theme: "mix", level: "facile" },
  { en: "sister", fr: "sœur", theme: "mix", level: "facile" },
  { en: "son", fr: "fils", theme: "mix", level: "moyen" },
  { en: "daughter", fr: "fille", theme: "mix", level: "moyen" },
  { en: "baby", fr: "bébé", theme: "mix", level: "facile" },
  { en: "child", fr: "enfant", theme: "mix", level: "facile" },
  { en: "children", fr: "enfants", theme: "mix", level: "moyen" },
  { en: "family", fr: "famille", theme: "mix", level: "facile" },
  { en: "friend", fr: "ami", theme: "mix", level: "facile" },
  { en: "people", fr: "personnes", theme: "mix", level: "moyen" },

  { en: "head", fr: "tête", theme: "mix", level: "facile" },
  { en: "face", fr: "visage", theme: "mix", level: "facile" },
  { en: "eye", fr: "œil", theme: "mix", level: "facile" },
  { en: "ear", fr: "oreille", theme: "mix", level: "facile" },
  { en: "nose", fr: "nez", theme: "mix", level: "facile" },
  { en: "mouth", fr: "bouche", theme: "mix", level: "facile" },
  { en: "hand", fr: "main", theme: "mix", level: "facile" },
  { en: "arm", fr: "bras", theme: "mix", level: "facile" },
  { en: "leg", fr: "jambe", theme: "mix", level: "facile" },
  { en: "foot", fr: "pied", theme: "mix", level: "facile" },
  { en: "heart", fr: "cœur", theme: "mix", level: "moyen" },
  { en: "body", fr: "corps", theme: "mix", level: "moyen" },

  { en: "water", fr: "eau", theme: "mix", level: "facile" },
  { en: "bread", fr: "pain", theme: "mix", level: "facile" },
  { en: "milk", fr: "lait", theme: "mix", level: "facile" },
  { en: "rice", fr: "riz", theme: "mix", level: "facile" },
  { en: "meat", fr: "viande", theme: "mix", level: "facile" },
  { en: "fish", fr: "poisson", theme: "animaux", level: "facile" },
  { en: "chicken", fr: "poulet", theme: "mix", level: "facile" },
  { en: "egg", fr: "œuf", theme: "mix", level: "facile" },
  { en: "cheese", fr: "fromage", theme: "mix", level: "moyen" },
  { en: "apple", fr: "pomme", theme: "mix", level: "facile" },
  { en: "banana", fr: "banane", theme: "mix", level: "facile" },
  { en: "orange fruit", fr: "orange", theme: "mix", level: "facile" },
  { en: "grape", fr: "raisin", theme: "mix", level: "moyen" },
  { en: "potato", fr: "pomme de terre", theme: "mix", level: "moyen" },
  { en: "tomato", fr: "tomate", theme: "mix", level: "facile" },
  { en: "carrot", fr: "carotte", theme: "mix", level: "moyen" },
  { en: "breakfast", fr: "petit déjeuner", theme: "mix", level: "moyen" },
  { en: "lunch", fr: "déjeuner", theme: "mix", level: "moyen" },
  { en: "dinner", fr: "dîner", theme: "mix", level: "moyen" },

  { en: "cat", fr: "chat", theme: "animaux", level: "facile" },
  { en: "dog", fr: "chien", theme: "animaux", level: "facile" },
  { en: "bird", fr: "oiseau", theme: "animaux", level: "facile" },
  { en: "horse", fr: "cheval", theme: "animaux", level: "moyen" },
  { en: "rabbit", fr: "lapin", theme: "animaux", level: "facile" },
  { en: "lion", fr: "lion", theme: "animaux", level: "facile" },
  { en: "tiger", fr: "tigre", theme: "animaux", level: "facile" },
  { en: "duck", fr: "canard", theme: "animaux", level: "facile" },
  { en: "cow", fr: "vache", theme: "animaux", level: "facile" },
  { en: "sheep", fr: "mouton", theme: "animaux", level: "moyen" },
  { en: "goat", fr: "chèvre", theme: "animaux", level: "moyen" },
  { en: "monkey", fr: "singe", theme: "animaux", level: "moyen" },
  { en: "elephant", fr: "éléphant", theme: "animaux", level: "moyen" },
  { en: "bear", fr: "ours", theme: "animaux", level: "moyen" },
  { en: "wolf", fr: "loup", theme: "animaux", level: "moyen" },
  { en: "snake", fr: "serpent", theme: "animaux", level: "moyen" },
  { en: "mouse", fr: "souris", theme: "animaux", level: "facile" },
  { en: "frog", fr: "grenouille", theme: "animaux", level: "moyen" },
  { en: "bee", fr: "abeille", theme: "animaux", level: "moyen" },
  { en: "butterfly", fr: "papillon", theme: "animaux", level: "moyen" },

  { en: "house", fr: "maison", theme: "maison", level: "facile" },
  { en: "home", fr: "chez soi", theme: "maison", level: "facile" },
  { en: "door", fr: "porte", theme: "maison", level: "facile" },
  { en: "window", fr: "fenêtre", theme: "maison", level: "facile" },
  { en: "room", fr: "pièce", theme: "maison", level: "facile" },
  { en: "bedroom", fr: "chambre", theme: "maison", level: "moyen" },
  { en: "kitchen", fr: "cuisine", theme: "maison", level: "facile" },
  { en: "bathroom", fr: "salle de bain", theme: "maison", level: "moyen" },
  { en: "living room", fr: "salon", theme: "maison", level: "moyen" },
  { en: "garden", fr: "jardin", theme: "maison", level: "facile" },
  { en: "table", fr: "table", theme: "maison", level: "facile" },
  { en: "chair", fr: "chaise", theme: "maison", level: "facile" },
  { en: "bed", fr: "lit", theme: "maison", level: "facile" },
  { en: "sofa", fr: "canapé", theme: "maison", level: "moyen" },
  { en: "lamp", fr: "lampe", theme: "maison", level: "facile" },
  { en: "television", fr: "télévision", theme: "maison", level: "moyen" },
  { en: "fridge", fr: "réfrigérateur", theme: "maison", level: "moyen" },
  { en: "stairs", fr: "escaliers", theme: "maison", level: "moyen" },
  { en: "wall", fr: "mur", theme: "maison", level: "facile" },
  { en: "floor", fr: "sol", theme: "maison", level: "moyen" },

  { en: "school", fr: "école", theme: "ecole", level: "facile" },
  { en: "book", fr: "livre", theme: "ecole", level: "facile" },
  { en: "pen", fr: "stylo", theme: "ecole", level: "facile" },
  { en: "pencil", fr: "crayon", theme: "ecole", level: "facile" },
  { en: "desk", fr: "bureau", theme: "ecole", level: "facile" },
  { en: "teacher", fr: "professeur", theme: "ecole", level: "moyen" },
  { en: "student", fr: "élève", theme: "ecole", level: "moyen" },
  { en: "lesson", fr: "leçon", theme: "ecole", level: "moyen" },
  { en: "answer", fr: "réponse", theme: "ecole", level: "moyen" },
  { en: "question", fr: "question", theme: "ecole", level: "moyen" },
  { en: "classroom", fr: "salle de classe", theme: "ecole", level: "moyen" },
  { en: "homework", fr: "devoirs", theme: "ecole", level: "moyen" },
  { en: "test", fr: "contrôle", theme: "ecole", level: "facile" },
  { en: "maths", fr: "mathématiques", theme: "ecole", level: "moyen" },
  { en: "history", fr: "histoire", theme: "ecole", level: "moyen" },
  { en: "science", fr: "science", theme: "ecole", level: "moyen" },
  { en: "language", fr: "langue", theme: "ecole", level: "moyen" },
  { en: "read", fr: "lire", theme: "ecole", level: "facile" },
  { en: "write", fr: "écrire", theme: "ecole", level: "facile" },
  { en: "learn", fr: "apprendre", theme: "ecole", level: "moyen" },

  { en: "run", fr: "courir", theme: "mix", level: "facile" },
  { en: "walk", fr: "marcher", theme: "mix", level: "facile" },
  { en: "jump", fr: "sauter", theme: "mix", level: "facile" },
  { en: "play", fr: "jouer", theme: "mix", level: "facile" },
  { en: "eat", fr: "manger", theme: "mix", level: "facile" },
  { en: "drink", fr: "boire", theme: "mix", level: "facile" },
  { en: "sleep", fr: "dormir", theme: "mix", level: "facile" },
  { en: "speak", fr: "parler", theme: "mix", level: "moyen" },
  { en: "listen", fr: "écouter", theme: "mix", level: "moyen" },
  { en: "look", fr: "regarder", theme: "mix", level: "facile" },
  { en: "see", fr: "voir", theme: "mix", level: "facile" },
  { en: "hear", fr: "entendre", theme: "mix", level: "moyen" },
  { en: "open", fr: "ouvrir", theme: "mix", level: "facile" },
  { en: "close", fr: "fermer", theme: "mix", level: "facile" },
  { en: "take", fr: "prendre", theme: "mix", level: "moyen" },
  { en: "give", fr: "donner", theme: "mix", level: "moyen" },
  { en: "come", fr: "venir", theme: "mix", level: "moyen" },
  { en: "go", fr: "aller", theme: "mix", level: "facile" },
  { en: "make", fr: "faire / fabriquer", theme: "mix", level: "moyen" },
  { en: "do", fr: "faire", theme: "mix", level: "moyen" },

  { en: "big", fr: "grand", theme: "mix", level: "facile" },
  { en: "small", fr: "petit", theme: "mix", level: "facile" },
  { en: "long", fr: "long", theme: "mix", level: "facile" },
  { en: "short", fr: "court", theme: "mix", level: "facile" },
  { en: "fast", fr: "rapide", theme: "mix", level: "facile" },
  { en: "slow", fr: "lent", theme: "mix", level: "facile" },
  { en: "hot", fr: "chaud", theme: "mix", level: "facile" },
  { en: "cold", fr: "froid", theme: "mix", level: "facile" },
  { en: "happy", fr: "heureux", theme: "mix", level: "facile" },
  { en: "sad", fr: "triste", theme: "mix", level: "facile" },
  { en: "angry", fr: "en colère", theme: "mix", level: "moyen" },
  { en: "tired", fr: "fatigué", theme: "mix", level: "moyen" },
  { en: "easy", fr: "facile", theme: "mix", level: "facile" },
  { en: "difficult", fr: "difficile", theme: "mix", level: "moyen" },
  { en: "new", fr: "nouveau", theme: "mix", level: "facile" },
  { en: "old", fr: "vieux", theme: "mix", level: "facile" },

  { en: "football", fr: "football", theme: "mix", level: "facile" },
  { en: "ball", fr: "ballon", theme: "mix", level: "facile" },
  { en: "goal", fr: "but", theme: "mix", level: "facile" },
  { en: "team", fr: "équipe", theme: "mix", level: "facile" },
  { en: "player", fr: "joueur", theme: "mix", level: "facile" },
  { en: "coach", fr: "entraîneur", theme: "mix", level: "moyen" },
  { en: "match", fr: "match", theme: "mix", level: "facile" },
  { en: "win", fr: "gagner", theme: "mix", level: "facile" },
  { en: "lose", fr: "perdre", theme: "mix", level: "facile" },
  { en: "training", fr: "entraînement", theme: "mix", level: "moyen" },
  { en: "goalkeeper", fr: "gardien de but", theme: "mix", level: "moyen" },
  { en: "stadium", fr: "stade", theme: "mix", level: "moyen" },

  { en: "Monday", fr: "lundi", theme: "mix", level: "moyen" },
  { en: "Tuesday", fr: "mardi", theme: "mix", level: "moyen" },
  { en: "Wednesday", fr: "mercredi", theme: "mix", level: "moyen" },
  { en: "Thursday", fr: "jeudi", theme: "mix", level: "moyen" },
  { en: "Friday", fr: "vendredi", theme: "mix", level: "moyen" },
  { en: "Saturday", fr: "samedi", theme: "mix", level: "moyen" },
  { en: "Sunday", fr: "dimanche", theme: "mix", level: "moyen" },
  { en: "today", fr: "aujourd'hui", theme: "mix", level: "facile" },
  { en: "tomorrow", fr: "demain", theme: "mix", level: "moyen" },
  { en: "yesterday", fr: "hier", theme: "mix", level: "moyen" },
  { en: "morning", fr: "matin", theme: "mix", level: "facile" },
  { en: "evening", fr: "soir", theme: "mix", level: "moyen" },
  { en: "night", fr: "nuit", theme: "mix", level: "facile" },

  { en: "car", fr: "voiture", theme: "mix", level: "facile" },
  { en: "bus", fr: "bus", theme: "mix", level: "facile" },
  { en: "train", fr: "train", theme: "mix", level: "facile" },
  { en: "bike", fr: "vélo", theme: "mix", level: "facile" },
  { en: "plane", fr: "avion", theme: "mix", level: "facile" },
  { en: "boat", fr: "bateau", theme: "mix", level: "facile" },
  { en: "road", fr: "route", theme: "mix", level: "facile" },
  { en: "street", fr: "rue", theme: "mix", level: "facile" },
  { en: "city", fr: "ville", theme: "mix", level: "facile" },
  { en: "country", fr: "pays", theme: "mix", level: "moyen" },
  { en: "world", fr: "monde", theme: "mix", level: "moyen" },

  { en: "I am hungry", fr: "j'ai faim", theme: "mix", level: "moyen" },
  { en: "I am thirsty", fr: "j'ai soif", theme: "mix", level: "moyen" },
  { en: "I like football", fr: "j'aime le football", theme: "mix", level: "moyen" },
  { en: "I love my family", fr: "j'aime ma famille", theme: "mix", level: "moyen" },
  { en: "Where is my book?", fr: "où est mon livre ?", theme: "ecole", level: "moyen" },
  { en: "Open the door", fr: "ouvre la porte", theme: "maison", level: "moyen" },
  { en: "Close the window", fr: "ferme la fenêtre", theme: "maison", level: "moyen" },
  { en: "Listen carefully", fr: "écoute attentivement", theme: "ecole", level: "moyen" },
  { en: "Read the sentence", fr: "lis la phrase", theme: "ecole", level: "moyen" },
  { en: "Write your name", fr: "écris ton nom", theme: "ecole", level: "moyen" },
  { en: "The cat is small", fr: "le chat est petit", theme: "animaux", level: "moyen" },
  { en: "The dog is big", fr: "le chien est grand", theme: "animaux", level: "moyen" },
  { en: "The sun is hot", fr: "le soleil est chaud", theme: "mix", level: "moyen" },
  { en: "The water is cold", fr: "l'eau est froide", theme: "mix", level: "moyen" },
  { en: "I can play", fr: "je peux jouer", theme: "mix", level: "moyen" },
  { en: "Can you help me?", fr: "peux-tu m'aider ?", theme: "mix", level: "moyen" },
  { en: "This is my house", fr: "c'est ma maison", theme: "maison", level: "moyen" },
  { en: "I go to school", fr: "je vais à l'école", theme: "ecole", level: "moyen" },
  { en: "He is my friend", fr: "c'est mon ami", theme: "mix", level: "moyen" },
  { en: "She is happy", fr: "elle est heureuse", theme: "mix", level: "moyen" }
];
